In [ ]:
import requests
from Credentials import CLIENT_ID, CLIENT_SECRET, engine_DEV_Final as engine
from BCDA_API import get_access_token


access_token = get_access_token()

response = requests.delete(
    'https://api.bcda.cms.gov/api/v3/jobs/177664',
    headers={
        "Accept": "application/fhir+json",
        "Authorization": f"Bearer {access_token}",
    }
)

Authenticating...
Token HTTP Status: 200
Access token acquired (prefix): eyJhbGciOiJSUzUxMiIs ...

In [7]:
response.headers

{'Date': 'Wed, 01 Jul 2026 15:50:29 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache; no-store; must-revalidate; max-age=0', 'Pragma': 'no-cache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Progress': 'In Progress (0%)'}

In [96]:
import polars as pl
from pathlib import Path
import pandas as pd
import duckdb

con = duckdb.connect()

df_eob = con.execute("select * from read_ndjson_auto('C:\\BCDA_V3\\Data\\ExplanationOfBenefit_v3_0137_20260706193338.ndjson', sample_size=-1, filename=true)").pl()
#df_patient = con.execute("select * from read_ndjson_auto('C:\\BCDA_V3\\Data\\Patient*.ndjson', sample_size=-1,union_by_name=true, filename=true)").pl()
#df_coverage = con.execute("select * from read_ndjson_auto('C:\\BCDA_V3\\Data\\Coverage*.ndjson', sample_size=-1,union_by_name=true, filename=true)").pl()

In [21]:
def flatten(df: pl.DataFrame, col: str) -> pl.DataFrame:
    return df.explode(col).unnest(col)
df_patient_race =(
df_patient
.select(['id', 'extension'])
.pipe(flatten, 'extension')
.select(['id', 'extension'])
.pipe(flatten, 'extension')
.select(['id','valueString'])
.filter(pl.col('valueString').is_not_null())
)

patient_base = (
    df_patient
    .select([
        "id",
        "name",
        "gender",
        "birthDate",
        "address",
        "deceasedDateTime",
        'filename',
        'meta',
        'link'
    ])
    .explode("address")
    .unnest("address")
    .explode("name")
    .unnest("name")
    .explode('link')
    .unnest('link')
    .with_columns(
        pl.col("given").list.join(", "),
        pl.col('meta').struct.field('lastUpdated'),
        pl.col('other').struct.field('display').alias('id_link')
    ).join(df_patient_race.select(['id', 'valueString']), on= 'id', how= 'left')
)

patient_base_sorted = (
    patient_base
    .with_columns(
    pl.col('valueString').alias('race'),
    pl.col('filename').str.split('\\').list.get(-1).alias('filename')
    )
    .select(
        "id",
        'id_link',
        'family',
        'given',
        "gender",
        'race',
        "birthDate",
        "postalCode",
        'state',
        "deceasedDateTime",
        'lastUpdated',
        'filename'
))

patient_base_sorted

shape: (2_567, 12)
┌───────────┬─────────┬───────────┬────────────┬───┬───────┬─────────────┬────────────┬────────────┐
│ id        ┆ id_link ┆ family    ┆ given      ┆ … ┆ state ┆ deceasedDat ┆ lastUpdate ┆ filename   │
│ ---       ┆ ---     ┆ ---       ┆ ---        ┆   ┆ ---   ┆ eTime       ┆ d          ┆ ---        │
│ str       ┆ str     ┆ str       ┆ str        ┆   ┆ str   ┆ ---         ┆ ---        ┆ str        │
│           ┆         ┆           ┆            ┆   ┆       ┆ date        ┆ datetime[μ ┆            │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ s]         ┆            │
╞═══════════╪═════════╪═══════════╪════════════╪═══╪═══════╪═════════════╪════════════╪════════════╡
│ 146341947 ┆ null    ┆ DOSS      ┆ WILLIAM, C ┆ … ┆ TX    ┆ null        ┆ 2026-05-24 ┆ Patient_v3 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 07:15:29.7 ┆ _0001_2026 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 60         ┆ 0706193338 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆            ┆ …          │
│ 164737228 ┆ null    ┆ THOMASON  ┆ LANA       ┆ … ┆ TX    ┆ null        ┆ 2026-06-19 ┆ Patient_v3 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 07:39:14.2 ┆ _0001_2026 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 70         ┆ 0706193338 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆            ┆ …          │
│ 142606117 ┆ null    ┆ WOOD      ┆ JUDITH     ┆ … ┆ AR    ┆ null        ┆ 2026-06-02 ┆ Patient_v3 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 09:42:15.3 ┆ _0001_2026 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 41         ┆ 0706193338 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆            ┆ …          │
│ 147591073 ┆ null    ┆ BARNES    ┆ JAMES, R   ┆ … ┆ TX    ┆ null        ┆ 2026-03-29 ┆ Patient_v3 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 21:19:18.7 ┆ _0001_2026 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 67         ┆ 0706193338 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆            ┆ …          │
│ 128045656 ┆ null    ┆ MCCORMICK ┆ WALTER, L  ┆ … ┆ TX    ┆ null        ┆ 2026-04-09 ┆ Patient_v3 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 01:16:58.3 ┆ _0001_2026 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 10         ┆ 0706193338 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆            ┆ …          │
│ …         ┆ …       ┆ …         ┆ …          ┆ … ┆ …     ┆ …           ┆ …          ┆ …          │
│ 113605516 ┆ null    ┆ HILLIS    ┆ JUDA       ┆ … ┆ TX    ┆ null        ┆ 2026-06-02 ┆ Patient_v3 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 09:42:15.3 ┆ _0005_2026 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 41         ┆ 0706193338 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆            ┆ …          │
│ 168261951 ┆ null    ┆ WILHOIT   ┆ JOHNNY, M  ┆ … ┆ TX    ┆ null        ┆ 2026-05-24 ┆ Patient_v3 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 09:42:08.4 ┆ _0005_2026 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 34         ┆ 0706193338 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆            ┆ …          │
│ 167546408 ┆ null    ┆ JORDAN    ┆ CHESLEY, D ┆ … ┆ TX    ┆ null        ┆ 2026-03-29 ┆ Patient_v3 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 21:29:42.8 ┆ _0005_2026 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 84         ┆ 0706193338 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆            ┆ …          │
│ 136163973 ┆ null    ┆ WELLS     ┆ CAROLYN    ┆ … ┆ TX    ┆ null        ┆ 2026-05-24 ┆ Patient_v3 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 09:12:00.5 ┆ _0005_2026 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 20         ┆ 0706193338 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆            ┆ …          │
│ 161497185 ┆ null    ┆ ROBBINS   ┆ CATE, E    ┆ … ┆ TX    ┆ null        ┆ 2026-05-24 ┆ Patient_v3 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 09:45:01.6 ┆ _0005_2026 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆ 21         ┆ 0706193338 │
│           ┆         ┆           ┆            ┆   ┆       ┆             ┆            ┆ …          │
└───────────┴─────────┴───────────┴────────────┴───┴───────┴─────────────┴────────────┴────────────┘

In [12]:
df_patient

shape: (22_156, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ address   ┆ birthDate ┆ communica ┆ extension ┆ … ┆ resourceT ┆ deceasedD ┆ link      ┆ filename │
│ ---       ┆ ---       ┆ tion      ┆ ---       ┆   ┆ ype       ┆ ateTime   ┆ ---       ┆ ---      │
│ list[stru ┆ date      ┆ ---       ┆ list[stru ┆   ┆ ---       ┆ ---       ┆ list[stru ┆ str      │
│ ct[2]]    ┆           ┆ list[stru ┆ ct[3]]    ┆   ┆ str       ┆ date      ┆ ct[2]]    ┆          │
│           ┆           ┆ ct[1]]    ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ [{"75604" ┆ 1971-03-0 ┆ [{{[{"unk ┆ [{"http:/ ┆ … ┆ Patient   ┆ null      ┆ null      ┆ C:\BCDA_ │
│ ,"TX"}]   ┆ 2         ┆ nown","ur ┆ /hl7.org/ ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│           ┆           ┆ n:ietf:bc ┆ fhir/us/c ┆   ┆           ┆           ┆           ┆ Patient_ │
│           ┆           ┆ p:4…      ┆ ore…      ┆   ┆           ┆           ┆           ┆ v3_000…  │
│ [{"75571" ┆ 1942-02-2 ┆ [{{[{"unk ┆ [{"http:/ ┆ … ┆ Patient   ┆ null      ┆ null      ┆ C:\BCDA_ │
│ ,"TX"}]   ┆ 8         ┆ nown","ur ┆ /hl7.org/ ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│           ┆           ┆ n:ietf:bc ┆ fhir/us/c ┆   ┆           ┆           ┆           ┆ Patient_ │
│           ┆           ┆ p:4…      ┆ ore…      ┆   ┆           ┆           ┆           ┆ v3_000…  │
│ [{"75567" ┆ 1961-04-1 ┆ [{{[{"unk ┆ [{"http:/ ┆ … ┆ Patient   ┆ null      ┆ null      ┆ C:\BCDA_ │
│ ,"TX"}]   ┆ 8         ┆ nown","ur ┆ /hl7.org/ ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│           ┆           ┆ n:ietf:bc ┆ fhir/us/c ┆   ┆           ┆           ┆           ┆ Patient_ │
│           ┆           ┆ p:4…      ┆ ore…      ┆   ┆           ┆           ┆           ┆ v3_000…  │
│ [{"75670" ┆ 1992-02-1 ┆ [{{[{"unk ┆ [{"http:/ ┆ … ┆ Patient   ┆ null      ┆ null      ┆ C:\BCDA_ │
│ ,"TX"}]   ┆ 5         ┆ nown","ur ┆ /hl7.org/ ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│           ┆           ┆ n:ietf:bc ┆ fhir/us/c ┆   ┆           ┆           ┆           ┆ Patient_ │
│           ┆           ┆ p:4…      ┆ ore…      ┆   ┆           ┆           ┆           ┆ v3_000…  │
│ [{"75691" ┆ 1955-11-2 ┆ [{{[{"unk ┆ [{"http:/ ┆ … ┆ Patient   ┆ null      ┆ null      ┆ C:\BCDA_ │
│ ,"TX"}]   ┆ 0         ┆ nown","ur ┆ /hl7.org/ ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│           ┆           ┆ n:ietf:bc ┆ fhir/us/c ┆   ┆           ┆           ┆           ┆ Patient_ │
│           ┆           ┆ p:4…      ┆ ore…      ┆   ┆           ┆           ┆           ┆ v3_000…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ [{"71846" ┆ 1956-05-0 ┆ [{{[{"unk ┆ [{"http:/ ┆ … ┆ Patient   ┆ null      ┆ null      ┆ C:\BCDA_ │
│ ,"AR"}]   ┆ 4         ┆ nown","ur ┆ /hl7.org/ ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│           ┆           ┆ n:ietf:bc ┆ fhir/us/c ┆   ┆           ┆           ┆           ┆ Patient_ │
│           ┆           ┆ p:4…      ┆ ore…      ┆   ┆           ┆           ┆           ┆ v3_000…  │
│ [{"75551" ┆ 1941-01-0 ┆ [{{[{"unk ┆ [{"http:/ ┆ … ┆ Patient   ┆ 2025-10-2 ┆ null      ┆ C:\BCDA_ │
│ ,"TX"}]   ┆ 6         ┆ nown","ur ┆ /hl7.org/ ┆   ┆           ┆ 0         ┆           ┆ V3\Data\ │
│           ┆           ┆ n:ietf:bc ┆ fhir/us/c ┆   ┆           ┆           ┆           ┆ Patient_ │
│           ┆           ┆ p:4…      ┆ ore…      ┆   ┆           ┆           ┆           ┆ v3_000…  │
│ [{"71822" ┆ 1938-03-1 ┆ [{{[{"unk ┆ [{"http:/ ┆ … ┆ Patient   ┆ null      ┆ null      ┆ C:\BCDA_ │
│ ,"AR"}]   ┆ 9         ┆ nown","ur ┆ /hl7.org/ ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│           ┆           ┆ n:ietf:bc ┆ fhir/us/c ┆   ┆           ┆           ┆           ┆ Patient_ │
│           ┆           ┆ p:4…      ┆ ore…      ┆   ┆           ┆           ┆           ┆ v3_000…  │
│ [{"75503" ┆ 1956-10-2 ┆ [{{[{"unk ┆ [{"http:/ ┆ … ┆ Patient   ┆ null      ┆ null      ┆ C:\BCDA_ │
│ ,"TX"}]   ┆ 1         ┆ nown","ur ┆ /hl7.org/ ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│           ┆           ┆ n:ietf:bc ┆ fhir/us/c ┆   ┆           ┆           ┆           ┆ Patient_ │
│           ┆           ┆ p:4…      ┆ ore…      ┆   ┆           ┆           ┆           ┆ v3_000…  │
│ [{"75644" ┆ 1941-12-0 ┆ [{{[{"unk ┆ [{"http:/ ┆ … ┆ Patient   ┆ 2025-11-1 ┆ null      ┆ C:\BCDA_ │
│ ,"TX"}]   ┆ 6         ┆ nown","ur ┆ /hl7.org/ ┆   ┆           ┆ 2         ┆           ┆ V3\Data\ │
│           ┆           ┆ n:ietf:bc ┆ fhir/us/c ┆   ┆           ┆           ┆           ┆ Patient_ │
│           ┆           ┆ p:4…      ┆ ore…      ┆   ┆           ┆           ┆           ┆ v3_000…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
df_patient_race =(
df_patient
.select(['id', 'extension'])
.explode('extension')
.unnest('extension')

)
df_patient_race

shape: (44_312, 4)
┌───────────┬─────────────────────────────────┬───────────┬─────────────────────────────────┐
│ id        ┆ url                             ┆ valueCode ┆ extension                       │
│ ---       ┆ ---                             ┆ ---       ┆ ---                             │
│ str       ┆ str                             ┆ str       ┆ list[struct[3]]                 │
╞═══════════╪═════════════════════════════════╪═══════════╪═════════════════════════════════╡
│ 176077134 ┆ http://hl7.org/fhir/us/core/St… ┆ 248152002 ┆ null                            │
│ 176077134 ┆ http://hl7.org/fhir/us/core/St… ┆ null      ┆ [{"ombCategory",{"2106-3","Whi… │
│ 109664215 ┆ http://hl7.org/fhir/us/core/St… ┆ 248153007 ┆ null                            │
│ 109664215 ┆ http://hl7.org/fhir/us/core/St… ┆ null      ┆ [{"ombCategory",{"2106-3","Whi… │
│ 181503373 ┆ http://hl7.org/fhir/us/core/St… ┆ 248152002 ┆ null                            │
│ …         ┆ …                               ┆ …         ┆ …                               │
│ 99908141  ┆ http://hl7.org/fhir/us/core/St… ┆ null      ┆ [{"ombCategory",{"2106-3","Whi… │
│ 164660944 ┆ http://hl7.org/fhir/us/core/St… ┆ 248153007 ┆ null                            │
│ 164660944 ┆ http://hl7.org/fhir/us/core/St… ┆ null      ┆ [{"ombCategory",{"2106-3","Whi… │
│ 109271272 ┆ http://hl7.org/fhir/us/core/St… ┆ 248153007 ┆ null                            │
│ 109271272 ┆ http://hl7.org/fhir/us/core/St… ┆ null      ┆ [{"ombCategory",{"2106-3","Whi… │
└───────────┴─────────────────────────────────┴───────────┴─────────────────────────────────┘

In [53]:
df_patient_linktable = (
    df_patient
    .filter(pl.col('identifier').is_not_null())
    .select(
        'id',
        'identifier',
        'filename',
        'meta'
    )
    .explode('identifier')
    .unnest('identifier')
    .select(
        'id',
        'period',
        'value',
        'filename',
        'meta'
    )
    .unnest('period')
    .with_columns(
        pl.col('meta').struct.field('lastUpdated')
    )
    .select(
        'id',
        'start',
        'end',
        'value',
        'lastUpdated',
        'filename'
    )
)
df_patient_linktable

shape: (26_686, 6)
┌───────────┬──────────────────┬─────────────────┬─────────────┬─────────────────┬─────────────────┐
│ id        ┆ start            ┆ end             ┆ value       ┆ lastUpdated     ┆ filename        │
│ ---       ┆ ---              ┆ ---             ┆ ---         ┆ ---             ┆ ---             │
│ str       ┆ datetime[μs]     ┆ datetime[μs]    ┆ str         ┆ datetime[μs]    ┆ str             │
╞═══════════╪══════════════════╪═════════════════╪═════════════╪═════════════════╪═════════════════╡
│ 176077134 ┆ 2024-08-13       ┆ null            ┆ 4T94HG4AW74 ┆ 2026-03-09      ┆ C:\BCDA_V3\Data │
│           ┆ 00:00:00         ┆                 ┆             ┆ 03:34:52.931    ┆ \Patient_v3_000 │
│           ┆                  ┆                 ┆             ┆                 ┆ …               │
│ 109664215 ┆ 2017-05-20       ┆ null            ┆ 2RP0GP3DU25 ┆ 2026-03-12      ┆ C:\BCDA_V3\Data │
│           ┆ 00:00:00         ┆                 ┆             ┆ 04:32:52.087    ┆ \Patient_v3_000 │
│           ┆                  ┆                 ┆             ┆                 ┆ …               │
│ 181503373 ┆ 2025-11-24       ┆ null            ┆ 5RU5PG9CA83 ┆ 2026-03-09      ┆ C:\BCDA_V3\Data │
│           ┆ 00:00:00         ┆                 ┆             ┆ 04:13:27.353    ┆ \Patient_v3_000 │
│           ┆                  ┆                 ┆             ┆                 ┆ …               │
│ 146341947 ┆ 2017-05-20       ┆ null            ┆ 5AU9NY9RE37 ┆ 2026-05-24      ┆ C:\BCDA_V3\Data │
│           ┆ 00:00:00         ┆                 ┆             ┆ 07:15:29.760    ┆ \Patient_v3_000 │
│           ┆                  ┆                 ┆             ┆                 ┆ …               │
│ 159744461 ┆ 2020-06-25       ┆ null            ┆ 4VY4QU5TF01 ┆ 2026-03-12      ┆ C:\BCDA_V3\Data │
│           ┆ 00:00:00         ┆                 ┆             ┆ 05:04:55.361    ┆ \Patient_v3_000 │
│           ┆                  ┆                 ┆             ┆                 ┆ …               │
│ …         ┆ …                ┆ …               ┆ …           ┆ …               ┆ …               │
│ 99908141  ┆ 2017-05-20       ┆ 2026-04-14      ┆ 8QK9N92NT31 ┆ 2026-03-11      ┆ C:\BCDA_V3\Data │
│           ┆ 00:00:00         ┆ 00:00:00        ┆             ┆ 21:09:00.092    ┆ \Patient_v3_000 │
│           ┆                  ┆                 ┆             ┆                 ┆ …               │
│ 99908141  ┆ 2026-04-14       ┆ null            ┆ 9PE5G68QM81 ┆ 2026-03-11      ┆ C:\BCDA_V3\Data │
│           ┆ 00:00:00         ┆                 ┆             ┆ 21:09:00.092    ┆ \Patient_v3_000 │
│           ┆                  ┆                 ┆             ┆                 ┆ …               │
│ 164660944 ┆ 2021-10-13       ┆ null            ┆ 4QA5CQ3EV84 ┆ 2026-03-12      ┆ C:\BCDA_V3\Data │
│           ┆ 00:00:00         ┆                 ┆             ┆ 06:12:30.355    ┆ \Patient_v3_000 │
│           ┆                  ┆                 ┆             ┆                 ┆ …               │
│ 109271272 ┆ 2017-05-20       ┆ 2025-01-13      ┆ 2FG0P32DK12 ┆ 2026-03-09      ┆ C:\BCDA_V3\Data │
│           ┆ 00:00:00         ┆ 00:00:00        ┆             ┆ 04:12:50.761    ┆ \Patient_v3_000 │
│           ┆                  ┆                 ┆             ┆                 ┆ …               │
│ 109271272 ┆ 2025-01-13       ┆ null            ┆ 5QK4Q60CU82 ┆ 2026-03-09      ┆ C:\BCDA_V3\Data │
│           ┆ 00:00:00         ┆                 ┆             ┆ 04:12:50.761    ┆ \Patient_v3_000 │
│           ┆                  ┆                 ┆             ┆                 ┆ …               │
└───────────┴──────────────────┴─────────────────┴─────────────┴─────────────────┴─────────────────┘

In [78]:
df_coverage_base = (
    df_coverage
    .select(
        'id',
        'beneficiary',
        'meta',
        'period',
        'payor',
        'status',
        'subscriberId',
        'filename'
    )
    .explode('payor')
    .unnest('payor')
    .unnest('period')
    .with_columns(
        pl.col('beneficiary')
        .struct.field('reference')
        .str.split('/')
        .list.get(1)
        .alias('patient_id'),
        pl.col('meta').struct.field('lastUpdated'),
    )
    .select(
        'id',
        'patient_id',
        'reference',
        'start',
        'end',
        'status',
        'subscriberId',
        'lastUpdated',
        'filename'
    )
)
df_coverage_base

shape: (2_634, 9)
┌────────────┬────────────┬───────────┬───────────┬───┬────────┬───────────┬───────────┬───────────┐
│ id         ┆ patient_id ┆ reference ┆ start     ┆ … ┆ status ┆ subscribe ┆ lastUpdat ┆ filename  │
│ ---        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---    ┆ rId       ┆ ed        ┆ ---       │
│ str        ┆ str        ┆ str       ┆ date      ┆   ┆ str    ┆ ---       ┆ ---       ┆ str       │
│            ┆            ┆           ┆           ┆   ┆        ┆ str       ┆ datetime[ ┆           │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆ μs]       ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ part-a-146 ┆ 146341947  ┆ #cms-org  ┆ 2017-06-0 ┆ … ┆ active ┆ 5AU9NY9RE ┆ 2026-05-2 ┆ C:\BCDA_V │
│ 341947     ┆            ┆           ┆ 1         ┆   ┆        ┆ 37        ┆ 4 07:15:2 ┆ 3\Data\Co │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆ 9.760     ┆ verage_v3 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ _04…      │
│ part-b-146 ┆ 146341947  ┆ #cms-org  ┆ 2017-06-0 ┆ … ┆ active ┆ 5AU9NY9RE ┆ 2026-05-2 ┆ C:\BCDA_V │
│ 341947     ┆            ┆           ┆ 1         ┆   ┆        ┆ 37        ┆ 4 07:15:2 ┆ 3\Data\Co │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆ 9.760     ┆ verage_v3 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ _04…      │
│ part-d-146 ┆ 146341947  ┆ #insurer- ┆ 2026-07-0 ┆ … ┆ active ┆ 5AU9NY9RE ┆ 2026-06-2 ┆ C:\BCDA_V │
│ 341947-S58 ┆            ┆ org       ┆ 1         ┆   ┆        ┆ 37        ┆ 6 08:38:3 ┆ 3\Data\Co │
│ 84-168     ┆            ┆           ┆           ┆   ┆        ┆           ┆ 2.811     ┆ verage_v3 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ _04…      │
│ dual-14634 ┆ 146341947  ┆ #cms-org  ┆ 2021-07-0 ┆ … ┆ active ┆ 5AU9NY9RE ┆ 2026-05-2 ┆ C:\BCDA_V │
│ 1947       ┆            ┆           ┆ 1         ┆   ┆        ┆ 37        ┆ 4 07:15:2 ┆ 3\Data\Co │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆ 9.760     ┆ verage_v3 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ _04…      │
│ part-a-175 ┆ 175267566  ┆ #cms-org  ┆ 2024-07-0 ┆ … ┆ active ┆ 5TV2QE7PC ┆ 2026-06-2 ┆ C:\BCDA_V │
│ 267566     ┆            ┆           ┆ 1         ┆   ┆        ┆ 96        ┆ 5 10:12:4 ┆ 3\Data\Co │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆ 7.118     ┆ verage_v3 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ _04…      │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …      ┆ …         ┆ …         ┆ …         │
│ part-b-161 ┆ 161497185  ┆ #cms-org  ┆ 2020-10-0 ┆ … ┆ active ┆ 4AY0V77DJ ┆ 2026-06-2 ┆ C:\BCDA_V │
│ 497185     ┆            ┆           ┆ 1         ┆   ┆        ┆ 35        ┆ 6 08:38:3 ┆ 3\Data\Co │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆ 2.769     ┆ verage_v3 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ _04…      │
│ part-c-161 ┆ 161497185  ┆ #insurer- ┆ 2026-02-0 ┆ … ┆ active ┆ 4AY0V77DJ ┆ 2026-06-2 ┆ C:\BCDA_V │
│ 497185-H22 ┆            ┆ org       ┆ 1         ┆   ┆        ┆ 35        ┆ 6 08:38:3 ┆ 3\Data\Co │
│ 93-014     ┆            ┆           ┆           ┆   ┆        ┆           ┆ 2.811     ┆ verage_v3 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ _04…      │
│ part-d-161 ┆ 161497185  ┆ #insurer- ┆ 2026-02-0 ┆ … ┆ active ┆ 4AY0V77DJ ┆ 2026-06-2 ┆ C:\BCDA_V │
│ 497185-H22 ┆            ┆ org       ┆ 1         ┆   ┆        ┆ 35        ┆ 6 08:38:3 ┆ 3\Data\Co │
│ 93-014     ┆            ┆           ┆           ┆   ┆        ┆           ┆ 2.811     ┆ verage_v3 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ _04…      │
│ part-a-179 ┆ 179476241  ┆ #cms-org  ┆ 2025-04-0 ┆ … ┆ active ┆ 5G33HK1NM ┆ 2026-06-2 ┆ C:\BCDA_V │
│ 476241     ┆            ┆           ┆ 1         ┆   ┆        ┆ 71        ┆ 7 12:01:0 ┆ 3\Data\Co │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆ 2.441     ┆ verage_v3 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ _04…      │
│ part-b-179 ┆ 179476241  ┆ #cms-org  ┆ 2025-04-0 ┆ … ┆ active ┆ 5G33HK1NM ┆ 2026-06-2 ┆ C:\BCDA_V │
│ 476241     ┆            ┆           ┆ 1         ┆   ┆        ┆ 71        ┆ 7 12:01:0 ┆ 3\Data\Co │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆ 2.441     ┆ verage_v3 │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆           ┆ _04…      │
└────────────┴────────────┴───────────┴───────────┴───┴────────┴───────────┴───────────┴───────────┘

In [32]:
column_names = [
    'coverage_id',
    'active',
    'contained_id',
    'name',
    'resourceType',
    'lastUpdated',
    'filename'
]

df_coverage_contained = (
    df_coverage
    .filter(pl.col('contained').is_not_null())
    .with_columns(
        pl.col('id').alias('coverage_id'),
        pl.col('meta').alias('meta_main')
    )
    .select(
        'coverage_id',
        'contained',
        'meta_main',
        'filename'
    )
    .explode('contained')
    .unnest('contained')
    .with_columns(
        pl.col('id').alias('contained_id'),
        pl.col('meta_main').struct.field('lastUpdated'),
        pl.col('filename').str.split('\\').list.get(-1).alias('filename')
    )
    .select(column_names)
)
df_coverage_contained

shape: (8_513, 7)
┌──────────────┬────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ coverage_id  ┆ active ┆ contained_id ┆ name         ┆ resourceType ┆ lastUpdated  ┆ filename     │
│ ---          ┆ ---    ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│ str          ┆ bool   ┆ str          ┆ str          ┆ str          ┆ datetime[μs] ┆ str          │
╞══════════════╪════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ part-a-14634 ┆ true   ┆ cms-org      ┆ Centers for  ┆ Organization ┆ 2026-05-24   ┆ Coverage_v3_ │
│ 1947         ┆        ┆              ┆ Medicare and ┆              ┆ 07:15:29.760 ┆ 0450_2026070 │
│              ┆        ┆              ┆ Medic…       ┆              ┆              ┆ 619333…      │
│ part-b-14634 ┆ true   ┆ cms-org      ┆ Centers for  ┆ Organization ┆ 2026-05-24   ┆ Coverage_v3_ │
│ 1947         ┆        ┆              ┆ Medicare and ┆              ┆ 07:15:29.760 ┆ 0450_2026070 │
│              ┆        ┆              ┆ Medic…       ┆              ┆              ┆ 619333…      │
│ part-d-14634 ┆ true   ┆ insurer-org  ┆ HUMANA       ┆ Organization ┆ 2026-06-26   ┆ Coverage_v3_ │
│ 1947-S5884-1 ┆        ┆              ┆ PREMIER RX   ┆              ┆ 08:38:32.811 ┆ 0450_2026070 │
│ 68           ┆        ┆              ┆ PLAN         ┆              ┆              ┆ 619333…      │
│ dual-1463419 ┆ true   ┆ cms-org      ┆ Centers for  ┆ Organization ┆ 2026-05-24   ┆ Coverage_v3_ │
│ 47           ┆        ┆              ┆ Medicare and ┆              ┆ 07:15:29.760 ┆ 0450_2026070 │
│              ┆        ┆              ┆ Medic…       ┆              ┆              ┆ 619333…      │
│ part-a-17526 ┆ true   ┆ cms-org      ┆ Centers for  ┆ Organization ┆ 2026-06-25   ┆ Coverage_v3_ │
│ 7566         ┆        ┆              ┆ Medicare and ┆              ┆ 10:12:47.118 ┆ 0450_2026070 │
│              ┆        ┆              ┆ Medic…       ┆              ┆              ┆ 619333…      │
│ …            ┆ …      ┆ …            ┆ …            ┆ …            ┆ …            ┆ …            │
│ part-b-16149 ┆ true   ┆ cms-org      ┆ Centers for  ┆ Organization ┆ 2026-06-26   ┆ Coverage_v3_ │
│ 7185         ┆        ┆              ┆ Medicare and ┆              ┆ 08:38:32.769 ┆ 0455_2026070 │
│              ┆        ┆              ┆ Medic…       ┆              ┆              ┆ 619333…      │
│ part-c-16149 ┆ true   ┆ insurer-org  ┆ AETNA        ┆ Organization ┆ 2026-06-26   ┆ Coverage_v3_ │
│ 7185-H2293-0 ┆        ┆              ┆ MEDICARE     ┆              ┆ 08:38:32.811 ┆ 0455_2026070 │
│ 14           ┆        ┆              ┆ SIGNATURE    ┆              ┆              ┆ 619333…      │
│              ┆        ┆              ┆ EXTRA        ┆              ┆              ┆              │
│ part-d-16149 ┆ true   ┆ insurer-org  ┆ AETNA        ┆ Organization ┆ 2026-06-26   ┆ Coverage_v3_ │
│ 7185-H2293-0 ┆        ┆              ┆ MEDICARE     ┆              ┆ 08:38:32.811 ┆ 0455_2026070 │
│ 14           ┆        ┆              ┆ SIGNATURE    ┆              ┆              ┆ 619333…      │
│              ┆        ┆              ┆ EXTRA        ┆              ┆              ┆              │
│ part-a-17947 ┆ true   ┆ cms-org      ┆ Centers for  ┆ Organization ┆ 2026-06-27   ┆ Coverage_v3_ │
│ 6241         ┆        ┆              ┆ Medicare and ┆              ┆ 12:01:02.441 ┆ 0455_2026070 │
│              ┆        ┆              ┆ Medic…       ┆              ┆              ┆ 619333…      │
│ part-b-17947 ┆ true   ┆ cms-org      ┆ Centers for  ┆ Organization ┆ 2026-06-27   ┆ Coverage_v3_ │
│ 6241         ┆        ┆              ┆ Medicare and ┆              ┆ 12:01:02.441 ┆ 0455_2026070 │
│              ┆        ┆              ┆ Medic…       ┆              ┆              ┆ 619333…      │
└──────────────┴────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [52]:
df_coverage_class = (
    df_coverage
    .filter(pl.col('class').is_not_null())
    .select(
        'id',
        'class',
        'meta',
        'filename'
    )
    .explode('class')
    .unnest('class')
    .with_columns(
        pl.col('meta').struct.field('lastUpdated'),
        pl.col('type').struct.field('coding').alias('type')
    )
    .explode('type')
    .unnest('type')
    .select(
        'id',
        'code',
        'value',
        'lastUpdated',
        'filename'
    )
)
df_coverage_class

shape: (5_444, 5)
┌──────────────────────────────┬─────────┬───────────┬───────────────┬─────────────────────────────┐
│ id                           ┆ code    ┆ value     ┆ lastUpdated   ┆ filename                    │
│ ---                          ┆ ---     ┆ ---       ┆ ---           ┆ ---                         │
│ str                          ┆ str     ┆ str       ┆ datetime[μs]  ┆ str                         │
╞══════════════════════════════╪═════════╪═══════════╪═══════════════╪═════════════════════════════╡
│ part-a-146341947             ┆ plan    ┆ Part A    ┆ 2026-05-24    ┆ C:\BCDA_V3\Data\Coverage_v3 │
│                              ┆         ┆           ┆ 07:15:29.760  ┆ _04…                        │
│ part-b-146341947             ┆ plan    ┆ Part B    ┆ 2026-05-24    ┆ C:\BCDA_V3\Data\Coverage_v3 │
│                              ┆         ┆           ┆ 07:15:29.760  ┆ _04…                        │
│ part-d-146341947-S5884-168   ┆ plan    ┆ Part D    ┆ 2026-06-26    ┆ C:\BCDA_V3\Data\Coverage_v3 │
│                              ┆         ┆           ┆ 08:38:32.811  ┆ _04…                        │
│ part-d-146341947-S5884-168   ┆ rxid    ┆ H72522509 ┆ 2026-06-26    ┆ C:\BCDA_V3\Data\Coverage_v3 │
│                              ┆         ┆           ┆ 08:38:32.811  ┆ _04…                        │
│ part-d-146341947-S5884-168   ┆ rxpcn   ┆ 03200000  ┆ 2026-06-26    ┆ C:\BCDA_V3\Data\Coverage_v3 │
│                              ┆         ┆           ┆ 08:38:32.811  ┆ _04…                        │
│ …                            ┆ …       ┆ …         ┆ …             ┆ …                           │
│ part-d-161497185-H2293-014   ┆ rxgroup ┆ RXAETD    ┆ 2026-06-26    ┆ C:\BCDA_V3\Data\Coverage_v3 │
│                              ┆         ┆           ┆ 08:38:32.811  ┆ _04…                        │
│ part-d-161497185-H2293-014   ┆ rxpcn   ┆ MEDDAET   ┆ 2026-06-26    ┆ C:\BCDA_V3\Data\Coverage_v3 │
│                              ┆         ┆           ┆ 08:38:32.811  ┆ _04…                        │
│ part-d-161497185-H2293-014   ┆ rxbin   ┆ 610502    ┆ 2026-06-26    ┆ C:\BCDA_V3\Data\Coverage_v3 │
│                              ┆         ┆           ┆ 08:38:32.811  ┆ _04…                        │
│ part-a-179476241             ┆ plan    ┆ Part A    ┆ 2026-06-27    ┆ C:\BCDA_V3\Data\Coverage_v3 │
│                              ┆         ┆           ┆ 12:01:02.441  ┆ _04…                        │
│ part-b-179476241             ┆ plan    ┆ Part B    ┆ 2026-06-27    ┆ C:\BCDA_V3\Data\Coverage_v3 │
│                              ┆         ┆           ┆ 12:01:02.441  ┆ _04…                        │
└──────────────────────────────┴─────────┴───────────┴───────────────┴─────────────────────────────┘

In [49]:
df_coverage_extension = (
    df_coverage
    .filter(pl.col('extension').is_not_null())
    .select(
        'id',
        'extension',
        'meta',
        'filename'
    )
    .explode('extension')
    .unnest('extension')
    .with_columns(
        pl.col('meta').struct.field('lastUpdated'),
        pl.col('valueCoding').struct.field('code').alias('code'),
        pl.col('valueCoding').struct.field('system').alias('system')
    )
    .select(
        'id',
        'code',
        'system',
        'lastUpdated',
        'filename'
    )
)
df_coverage_extension

shape: (13_226, 5)
┌──────────────────┬──────┬────────────────────────────┬───────────────┬───────────────────────────┐
│ id               ┆ code ┆ system                     ┆ lastUpdated   ┆ filename                  │
│ ---              ┆ ---  ┆ ---                        ┆ ---           ┆ ---                       │
│ str              ┆ str  ┆ str                        ┆ datetime[μs]  ┆ str                       │
╞══════════════════╪══════╪════════════════════════════╪═══════════════╪═══════════════════════════╡
│ part-a-146341947 ┆ D    ┆ https://bluebutton.cms.gov ┆ 2026-05-24    ┆ C:\BCDA_V3\Data\Coverage_ │
│                  ┆      ┆ /fhi…                      ┆ 07:15:29.760  ┆ v3_04…                    │
│ part-a-146341947 ┆ E    ┆ https://bluebutton.cms.gov ┆ 2026-05-24    ┆ C:\BCDA_V3\Data\Coverage_ │
│                  ┆      ┆ /fhi…                      ┆ 07:15:29.760  ┆ v3_04…                    │
│ part-a-146341947 ┆ 20   ┆ https://bluebutton.cms.gov ┆ 2026-05-24    ┆ C:\BCDA_V3\Data\Coverage_ │
│                  ┆      ┆ /fhi…                      ┆ 07:15:29.760  ┆ v3_04…                    │
│ part-a-146341947 ┆ N    ┆ https://bluebutton.cms.gov ┆ 2026-05-24    ┆ C:\BCDA_V3\Data\Coverage_ │
│                  ┆      ┆ /fhi…                      ┆ 07:15:29.760  ┆ v3_04…                    │
│ part-a-146341947 ┆ Y    ┆ https://bluebutton.cms.gov ┆ 2026-05-24    ┆ C:\BCDA_V3\Data\Coverage_ │
│                  ┆      ┆ /fhi…                      ┆ 07:15:29.760  ┆ v3_04…                    │
│ …                ┆ …    ┆ …                          ┆ …             ┆ …                         │
│ part-b-179476241 ┆ Y    ┆ https://bluebutton.cms.gov ┆ 2026-06-27    ┆ C:\BCDA_V3\Data\Coverage_ │
│                  ┆      ┆ /fhi…                      ┆ 12:01:02.441  ┆ v3_04…                    │
│ part-b-179476241 ┆ 10   ┆ https://bluebutton.cms.gov ┆ 2026-06-27    ┆ C:\BCDA_V3\Data\Coverage_ │
│                  ┆      ┆ /fhi…                      ┆ 12:01:02.441  ┆ v3_04…                    │
│ part-b-179476241 ┆ N    ┆ https://bluebutton.cms.gov ┆ 2026-06-27    ┆ C:\BCDA_V3\Data\Coverage_ │
│                  ┆      ┆ /fhi…                      ┆ 12:01:02.441  ┆ v3_04…                    │
│ part-b-179476241 ┆ N    ┆ https://bluebutton.cms.gov ┆ 2026-06-27    ┆ C:\BCDA_V3\Data\Coverage_ │
│                  ┆      ┆ /fhi…                      ┆ 12:01:02.441  ┆ v3_04…                    │
│ part-b-179476241 ┆ 0    ┆ https://bluebutton.cms.gov ┆ 2026-06-27    ┆ C:\BCDA_V3\Data\Coverage_ │
│                  ┆      ┆ /fhi…                      ┆ 12:01:02.441  ┆ v3_04…                    │
└──────────────────┴──────┴────────────────────────────┴───────────────┴───────────────────────────┘

In [15]:
from datetime import datetime
now = datetime.now().strftime('%d/%m/%Y %H:%M:%S')
def process_eob_base(df_eob: pl.DataFrame):  
    
    def safe_expr(df, source_col, expr, alias):
        if source_col in df.columns:
            return expr.alias(alias)
        return pl.lit(None).alias(alias)
    column_names = [
            'claim_id',
            'cntrl_num',
            'billablePeriod_start',
            'billablePeriod_end',
            'payment_amount',
            'payment_date',
            'patient_id',
            'provider_id',
            'outcome',
            'type_code',
            'type_display',
            'type_code_display',
            'related_value',
            'related_relationship',
            'source',
            'final_action',
            'created',
            'lastUpdated',
            'filename',
            'extract_date'
    ]
    
    df_eob_base = (
        df_eob
        .explode('identifier')
        .with_columns(
            pl.col('identifier').struct.field('value').alias('cntrl_num'),
            pl.col('identifier').struct.field('system').alias('idt_system'),
            pl.col('id').alias('claim_id'),
            pl.col('filename').str.split('\\').list.get(-1).alias('filename')
        )
        .filter(pl.col('idt_system').is_not_null())
        .with_columns(
            pl.lit(now).alias('extract_date')
        )
    )
    
    expres = [
        safe_expr(
            df_eob_base,
            'billablePeriod',
            pl.col('billablePeriod').struct.field('start'),
            'billablePeriod_start'
        ),
        safe_expr(
            df_eob_base,
            'billablePeriod',
            pl.col('billablePeriod').struct.field('end'),
            'billablePeriod_end'
        ),
        safe_expr(
            df_eob_base,
            'payment',
            pl.col('payment').struct.field('amount').struct.field('value'),
            'payment_amount'
        ),
        safe_expr(
            df_eob_base,
            'payment',
            pl.col('payment').struct.field('date'),
            'payment_date'
        ),
        safe_expr(
            df_eob_base,
            'patient',
            pl.col('patient').struct.field('reference').str.split('/').list.get(1),
            'patient_id'
        ),
        safe_expr(
            df_eob_base,
            'provider',
            pl.col('provider').struct.field('reference').str.replace('#',''),
            'provider_id'
        ),
        safe_expr(
            df_eob_base,
            'type',
            pl.col('type').struct.field('coding').list.get(0).struct.field('code'),
            'type_code'
        ),
        safe_expr(
            df_eob_base,
            'type',
            pl.col('type').struct.field('coding').list.get(0).struct.field('display'),
            'type_display'
        ),
        safe_expr(
            df_eob_base,
            'type',
            pl.col('type').struct.field('coding').list.get(1).struct.field('code'),
            'type_code_display'
        ),
        safe_expr(
            df_eob_base,
            'meta',
            pl.col('meta').struct.field('lastUpdated'),
            'lastUpdated'
        ),
        safe_expr(
            df_eob_base,
            'meta',
            pl.col('meta').struct.field('tag').list.get(0).struct.field('code'),
            'source'
        ),
        safe_expr(
            df_eob_base,
            'meta',
            pl.col('meta').struct.field('tag').list.get(1).struct.field('code'),
            'final_action'
        ),
        safe_expr(
            df_eob_base,
            'related',
            pl.col('related').list.get(0).struct.field('reference').struct.field('value'),
            'related_value'
        ),
        safe_expr(
            df_eob_base,
            'related',
            pl.col('related').list.get(0).struct.field('relationship').struct.field('coding').list.get(0).struct.field('code'),
            'related_relationship'
        ),
    ]
    
    df_eob_base = (
        df_eob_base
        .with_columns(expres)
        .select(column_names)
    )
    
    return df_eob_base.to_pandas()

process_eob_base(df_eob)

,claim_id,cntrl_num,billablePeriod_start,billablePeriod_end,payment_amount,payment_date,patient_id,provider_id,outcome,type_code,type_display,type_code_display,related_value,related_relationship,source,final_action,created,lastUpdated,filename,extract_date
0,511819681320,4756869170498930764756869170498930762FGA,2026-06-02,2026-06-02,NaN,NaT,176494789,1205448255,complete,1,MEDICARE PART D ORIGINAL CLAIM,pharmacy,None,None,DDPS,FinalAction,2026-06-04,2026-06-05 03:44:07.098,ExplanationOfBenefit_v3_0025_20260701181421.nd...,06/07/2026 15:36:19
1,511819681483,7262935802498936637262935802498936632FGA,2026-06-02,2026-06-02,NaN,NaT,176494789,1205448255,complete,1,MEDICARE PART D ORIGINAL CLAIM,pharmacy,None,None,DDPS,FinalAction,2026-06-04,2026-06-05 03:44:07.098,ExplanationOfBenefit_v3_0025_20260701181421.nd...,06/07/2026 15:36:19
2,512023760208,4539300282219937434539300282219937432FGA,2026-06-23,2026-06-23,NaN,NaT,176494789,1205448255,complete,1,MEDICARE PART D ORIGINAL CLAIM,pharmacy,None,None,DDPS,FinalAction,2026-06-25,2026-06-26 01:34:31.686,ExplanationOfBenefit_v3_0025_20260701181421.nd...,06/07/2026 15:36:19
3,1006337976064,452926147179190,2026-05-19,2026-05-19,205.97,2026-05-30,176494789,1619977295,complete,71,MEDICARE PART B PROFESSIONAL PHYSICIAN/SUPPLIE...,professional,None,None,NationalClaimsHistory,FinalAction,2026-06-05,2026-06-09 01:21:00.641,ExplanationOfBenefit_v3_0025_20260701181421.nd...,06/07/2026 15:36:19
4,1006337976078,452926147380840,2026-04-07,2026-04-07,74.04,2026-06-03,176494789,1619977295,complete,71,MEDICARE PART B PROFESSIONAL PHYSICIAN/SUPPLIE...,professional,None,None,NationalClaimsHistory,FinalAction,2026-06-05,2026-06-09 01:21:00.641,ExplanationOfBenefit_v3_0025_20260701181421.nd...,06/07/2026 15:36:19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,512001788219,3395039311809932233395039311809932232BUA,2026-06-18,2026-06-18,NaN,2026-06-30,173121213,1326426768,complete,1,MEDICARE PART D ORIGINAL CLAIM,pharmacy,None,None,DDPS,NotFinalAction,2026-06-22,2026-06-25 01:53:15.646,ExplanationOfBenefit_v3_0025_20260701181421.nd...,06/07/2026 15:36:19
720,512001791498,6235850523509934466235850523509934462BUA,2026-06-15,2026-06-15,NaN,NaT,173121213,1326426768,complete,3,MEDICARE PART D DELETED CLAIM,pharmacy,None,None,DDPS,NotFinalAction,2026-06-22,2026-06-23 03:17:14.558,ExplanationOfBenefit_v3_0025_20260701181421.nd...,06/07/2026 15:36:19
721,512019068259,3395039311809932233395039311809932232BUA,2026-06-18,2026-06-18,NaN,NaT,173121213,1326426768,complete,3,MEDICARE PART D DELETED CLAIM,pharmacy,None,None,DDPS,NotFinalAction,2026-06-24,2026-06-25 02:08:09.177,ExplanationOfBenefit_v3_0025_20260701181421.nd...,06/07/2026 15:36:19
722,512055721304,8609008762019931148609008762019931142BUA,2026-06-21,2026-06-21,NaN,2026-07-07,173121213,1558443911,complete,1,MEDICARE PART D ORIGINAL CLAIM,pharmacy,None,None,DDPS,FinalAction,2026-06-29,2026-06-30 03:19:16.424,ExplanationOfBenefit_v3_0025_20260701181421.nd...,06/07/2026 15:36:19
723,1006359630717,22615502770807TXA,2026-05-07,2026-05-07,49.51,2026-06-18,173121213,1295736734,complete,40,MEDICARE OUTPATIENT CLAIM,institutional,None,None,NationalClaimsHistory,FinalAction,2026-06-12,2026-06-16 02:11:11.310,ExplanationOfBenefit_v3_0025_20260701181421.nd...,06/07/2026 15:36:19

In [ ]:
def process_eob_base(df_eob: pl.DataFrame):        
    df_eob_base = (
        df_eob
        .select(
            'id',
            'billablePeriod',
            'created',
            'payment',
            'patient',
            'provider',
            'outcome',
            'identifier',
            'insurance',
            'type',
            'meta',
            'related',
            'filename'
        )
        .explode('identifier')
        .with_columns(
            pl.col('identifier').struct.field('value').alias('cntrl_num'),
            pl.col('identifier').struct.field('system').alias('idt_system'),
        )
        .filter(pl.col('idt_system').is_not_null())
        .with_columns(
            pl.col('billablePeriod').struct.field('start').alias('billablePeriod_start'),
            pl.col('billablePeriod').struct.field('end').alias('billablePeriod_end'),
            pl.col('payment').struct.field('amount').alias('payment_amount'),
            pl.col('payment').struct.field('date').alias('payment_date'),
            pl.col('patient').struct.field('reference').str.split('/').list.get(1).alias('patient_id'),
            pl.col('provider').struct.field('reference').str.replace('#','').alias('provider_id'),
            pl.col('type').struct.field('coding').list.get(0).struct.field('code').alias('type_code'),
            pl.col('type').struct.field('coding').list.get(0).struct.field('display').alias('type_display'),
            pl.col('type').struct.field('coding').list.get(1).struct.field('code').alias('type_code_display'),
            pl.col('meta').struct.field('lastUpdated'),
            pl.col('meta').struct.field('tag').list.get(0).struct.field('code').alias('source'),
            pl.col('meta').struct.field('tag').list.get(1).struct.field('code').alias('final_action'),
            pl.col('related').list.get(0).struct.field('reference'),
            pl.col('related').list.get(0).struct.field('relationship'),
            pl.lit(now).alias('extract_date')
        )
        .with_columns(
            pl.col('payment_amount').struct.field('value').alias('payment_amount'),
            pl.col('reference').struct.field('value').alias('related_value'),
            pl.col('relationship').struct.field('coding').list.get(0).struct.field('code').alias('related_relationship')
        )
        .select(
            'id',
            'cntrl_num',
            'billablePeriod_start',
            'billablePeriod_end',
            'payment_amount',
            'payment_date',
            'patient_id',
            'provider_id',
            'outcome',
            'type_code',
            'type_display',
            'type_code_display',
            'related_value',
            'related_relationship',
            'source',
            'final_action',
            'created',
            'lastUpdated',
            'filename',
            'extract_date'
        )
    )
    return df_eob_base.to_pandas()

shape: (244_161, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ cntrl_num ┆ billableP ┆ billableP ┆ … ┆ final_act ┆ created   ┆ lastUpdat ┆ filename │
│ ---       ┆ ---       ┆ eriod_sta ┆ eriod_end ┆   ┆ ion       ┆ ---       ┆ ed        ┆ ---      │
│ str       ┆ str       ┆ rt        ┆ ---       ┆   ┆ ---       ┆ datetime[ ┆ ---       ┆ str      │
│           ┆           ┆ ---       ┆ date      ┆   ┆ str       ┆ μs]       ┆ datetime[ ┆          │
│           ┆           ┆ date      ┆           ┆   ┆           ┆           ┆ μs]       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 100432454 ┆ 452224295 ┆ 2024-10-1 ┆ 2024-10-1 ┆ … ┆ FinalActi ┆ 2024-10-2 ┆ 2026-03-0 ┆ C:\BCDA_ │
│ 5686      ┆ 902980    ┆ 4         ┆ 4         ┆   ┆ on        ┆ 5         ┆ 8 09:36:2 ┆ V3\Data\ │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00:00:00  ┆ 5.384     ┆ Explanat │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ 100435782 ┆ 453224296 ┆ 2024-09-0 ┆ 2024-09-0 ┆ … ┆ FinalActi ┆ 2024-11-0 ┆ 2026-03-0 ┆ C:\BCDA_ │
│ 1502      ┆ 753690    ┆ 5         ┆ 5         ┆   ┆ on        ┆ 1         ┆ 8 11:46:0 ┆ V3\Data\ │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00:00:00  ┆ 0.861     ┆ Explanat │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ 100435782 ┆ 224298018 ┆ 2024-09-0 ┆ 2024-09-0 ┆ … ┆ FinalActi ┆ 2024-11-0 ┆ 2026-03-0 ┆ C:\BCDA_ │
│ 2988      ┆ 07107TXA  ┆ 5         ┆ 5         ┆   ┆ on        ┆ 1         ┆ 7 10:43:5 ┆ V3\Data\ │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00:00:00  ┆ 5.187     ┆ Explanat │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ 100437706 ┆ 452224305 ┆ 2024-09-2 ┆ 2024-09-2 ┆ … ┆ FinalActi ┆ 2024-11-0 ┆ 2026-03-0 ┆ C:\BCDA_ │
│ 5539      ┆ 400900    ┆ 4         ┆ 4         ┆   ┆ on        ┆ 8         ┆ 9 01:19:5 ┆ V3\Data\ │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00:00:00  ┆ 6.899     ┆ Explanat │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ 100437706 ┆ 224297001 ┆ 2024-09-0 ┆ 2024-09-0 ┆ … ┆ FinalActi ┆ 2024-11-0 ┆ 2026-03-0 ┆ C:\BCDA_ │
│ 6394      ┆ 02107NTA  ┆ 4         ┆ 4         ┆   ┆ on        ┆ 8         ┆ 7 18:14:1 ┆ V3\Data\ │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00:00:00  ┆ 5.038     ┆ Explanat │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 100635890 ┆ 226154007 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ FinalActi ┆ 2026-06-1 ┆ 2026-06-1 ┆ C:\BCDA_ │
│ 0507      ┆ 13804ARA  ┆ 7         ┆ 7         ┆   ┆ on        ┆ 2         ┆ 6 02:10:4 ┆ V3\Data\ │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00:00:00  ┆ 9.155     ┆ Explanat │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ 100640897 ┆ 520226167 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ FinalActi ┆ 2026-06-2 ┆ 2026-06-3 ┆ C:\BCDA_ │
│ 0910      ┆ 312860    ┆ 6         ┆ 6         ┆   ┆ on        ┆ 6         ┆ 0 01:49:5 ┆ V3\Data\ │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00:00:00  ┆ 6.241     ┆ Explanat │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ 100633797 ┆ 452826149 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ FinalActi ┆ 2026-06-0 ┆ 2026-06-0 ┆ C:\BCDA_ │
│ 1749      ┆ 142220    ┆ 7         ┆ 7         ┆   ┆ on        ┆ 5         ┆ 9 01:21:0 ┆ V3\Data\ │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00:00:00  ┆ 0.072     ┆ Explanat │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ 100633797 ┆ 226152078 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ FinalActi ┆ 2026-06-0 ┆ 2026-06-0 ┆ C:\BCDA_ │
│ 2436      ┆ 66807TXA  ┆ 7         ┆ 7         ┆   ┆ on        ┆ 5         ┆ 9 01:01:4 ┆ V3\Data\ │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00:00:00  ┆ 3.513     ┆ Explanat │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ 100635963 ┆ 452826153 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ FinalActi ┆ 2026-06-1 ┆ 2026-06-1 ┆ C:\BCDA_ │
│ 1211      ┆ 480410    ┆ 7         ┆ 7         ┆   ┆ on        ┆ 2         ┆ 6 02:21:5 ┆ V3\Data\ │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00:00:00  ┆ 7.152     ┆ Explanat │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ionOfB…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:
def process_eob_diagnosis(df_eob: pl.DataFrame):
    df_eob_diagnosis = (
        df_eob
        .filter(pl.col('diagnosis').is_not_null())
        .select(
            'id',
            'diagnosis',
            'meta',
            'patient',
            'filename'
        )
        .pipe(flatten, 'diagnosis')
        .with_columns(
            pl.col('diagnosisCodeableConcept').struct.field('coding').list.get(0).struct.field('code').alias('diagnosis_code'),
            pl.col('diagnosisCodeableConcept').struct.field('coding').list.get(0).struct.field('system').str.split('/').list.get(-1).alias('diagnosis_system'),
            pl.col('type').list.get(0).struct.field('coding').list.get(0).struct.field('code').alias('diagnosis_type_code'),
            pl.col('meta').struct.field('lastUpdated').alias('lastUpdated'),
            pl.col('patient').struct.field('reference').str.split('/').list.get(1).alias('patient_id'),
            pl.col('onAdmission').struct.field('coding').list.get(0).struct.field('code').alias('onAdmission'),
            pl.lit(now).alias('extract_date'),
            pl.col('filename').str.split('\\').list.get(-1).alias('filename')
        )
        .select(
            'id',
            'diagnosis_code',
            'diagnosis_system',
            'diagnosis_type_code',
            'onAdmission',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
        )
    )
    return df_eob_diagnosis.to_pandas()
process_eob_diagnosis(df_eob)

NameError: name 'flatten' is not defined

In [16]:
from datetime import datetime

now = datetime.now().strftime('%d/%m/%Y %H:%M:%S')

def process_eob_diagnosis(df_eob: pl.DataFrame):
    
    def safe_expr(df, source_col, expr, alias):
        if source_col in df.columns:
            return expr.alias(alias)
        return pl.lit(None).alias(alias)
    
    column_names = [
            'id',
            'diagnosis_code',
            'diagnosis_system',
            'diagnosis_type_code',
            'onAdmission',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
    ]
    
    df_eob_diagnosis = (
        df_eob
        .filter(pl.col('diagnosis').is_not_null())
        .select(
            'id',
            'diagnosis',
            'meta',
            'patient',
            'filename'
        )
        .pipe(flatten, 'diagnosis')
        .with_columns(
            pl.lit(now).alias('extract_date')
        )
    )
    
    epres = [
        safe_expr(
            df_eob_diagnosis,
            'diagnosisCodeableConcept',
            pl.col('diagnosisCodeableConcept').struct.field('coding').list.get(0).struct.field('code'),
            'diagnosis_code'
        ),
        safe_expr(
            df_eob_diagnosis,
            'diagnosisCodeableConcept',
            pl.col('diagnosisCodeableConcept').struct.field('coding').list.get(0).struct.field('system').str.split('/').list.get(-1),
            'diagnosis_system'
        ),
        safe_expr(
            df_eob_diagnosis,
            'type',
            pl.col('type').list.get(0).struct.field('coding').list.get(0).struct.field('code'),
            'diagnosis_type_code'
        ),
        safe_expr(
            df_eob_diagnosis,
            'meta',
            pl.col('meta').struct.field('lastUpdated'),
            'lastUpdated'
        ),
        safe_expr(
            df_eob_diagnosis,
            'patient',
            pl.col('patient').struct.field('reference').str.split('/').list.get(1),
            'patient_id'
        ),
        safe_expr(
            df_eob_diagnosis,
            'onAdmission',
            pl.col('onAdmission').struct.field('coding').list.get(0).struct.field('code'),
            'onAdmission'
        ),
    ]
    
    df_eob_diagnosis = (
        df_eob_diagnosis
        .with_columns(epres)
        .select(column_names)
    )
    return df_eob_diagnosis.to_pandas()

process_eob_diagnosis(df_eob)

NameError: name 'flatten' is not defined

In [156]:
def process_eob_procedure(df_eob: pl.DataFrame):
    
    def safe_expr(df, source_col, expr, alias):
        if source_col in df.columns:
            return expr.alias(alias)
        return pl.lit(None).alias(alias)
    
    column_names = [
            'id',
            'sequence',
            'procedure_code',
            'code_system',
            'type_code',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
    ]
    
    df_eob_procedure = (
        df_eob
        .filter(pl.col('procedure').is_not_null())
        .select(
            'id',
            'procedure',
            'meta',
            'patient',
            'filename'
        )
        .pipe(flatten, 'procedure')
        .with_columns(
            pl.lit(now).alias('extract_date')
        )
    )
    
    expres = [
        safe_expr(
            df_eob_procedure,
            'procedureCodeableConcept',
            pl.col('procedureCodeableConcept').struct.field('coding').list.get(0).struct.field('code'),
            'procedure_code'
        ),
        safe_expr(
            df_eob_procedure,
            'procedureCodeableConcept',
            pl.col('procedureCodeableConcept').struct.field('coding').list.get(0).struct.field('system').str.split('/').list.get(-1),
            'code_system'
        ),
        safe_expr(
            df_eob_procedure,
            'type',
            pl.col('type').list.get(0).struct.field('coding').list.get(0).struct.field('code'),
            'type_code'
        ),
        safe_expr(
            df_eob_procedure,
            'meta',
            pl.col('meta').struct.field('lastUpdated'),
            'lastUpdated'
        ),
        safe_expr(
            df_eob_procedure,
            'patient',
            pl.col('patient').struct.field('reference').str.split('/').list.get(1),
            'patient_id'
        )
    ]
    
    df_eob_procedure = (
        df_eob_procedure
        .with_columns(expres)
        .select(column_names)
    )
    
    return df_eob_procedure.to_pandas()

process_eob_procedure(df_eob)

,id,sequence,procedure_code,code_system,type_code,patient_id,lastUpdated,filename,extract_date
0,1002285493712,1,0SP004Z,ICD10,principal,145393328,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
1,1002285493712,2,0SG1071,ICD10,other,145393328,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
2,1002285493712,3,01NB0ZZ,ICD10,other,145393328,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
3,1002285493712,4,07DR3ZZ,ICD10,other,145393328,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
4,1002285493712,5,4A11X4G,ICD10,other,145393328,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
5,1002623273216,1,0SR902Z,ICD10,principal,145393328,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
6,1001453297593,1,0QS906Z,ICD10,principal,108045823,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
7,1002623975383,1,06CN3ZZ,ICD10,principal,147614476,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
8,1002623975383,2,06CY3ZZ,ICD10,other,147614476,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
9,1001429491450,1,01NB0ZZ,ICD10,principal,120266696,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
10,1001429491450,2,00NY0ZZ,ICD10,other,120266696,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
11,1001429491450,3,00QT0ZZ,ICD10,other,120266696,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
12,1001429491450,4,00UT0KZ,ICD10,other,120266696,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
13,1001286709980,1,0T9B70Z,ICD10,principal,106326851,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
14,1001453526530,1,BQ0HZZZ,ICD10,principal,106326851,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
15,1001453526530,2,2W3DX1Z,ICD10,other,106326851,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
16,1002007888499,1,0JH632Z,ICD10,principal,106326851,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
17,1002007888499,2,3E02340,ICD10,other,106326851,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
18,1002482083157,1,02L73DK,ICD10,principal,106326851,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
19,1002525460287,1,02HV33Z,ICD10,principal,67364464,2026-04-30 18:28:59.785,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
20,1006359611724,1,0SG1071,ICD10,principal,138993899,2026-06-16 02:03:44.911,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
21,1006359611724,2,00NY0ZZ,ICD10,other,138993899,2026-06-16 02:03:44.911,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
22,1006359611724,3,01NB0ZZ,ICD10,other,138993899,2026-06-16 02:03:44.911,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33
23,1006359611724,4,0QP004Z,ICD10,other,138993899,2026-06-16 02:03:44.911,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0137_2...,06/07/2026 15:49:33

In [ ]:
def process_eob_procedure(df_eob: pl.DataFrame):
    df_eob_procedure = (
        df_eob
        .filter(pl.col('procedure').is_not_null())
        .select(
            'id',
            'procedure',
            'meta',
            'patient',
            'filename'
        )
        .pipe(flatten, 'procedure')
        .with_columns(
            pl.col('procedureCodeableConcept').struct.field('coding').list.get(0).struct.field('code').alias('procedure_code'),
            pl.col('procedureCodeableConcept').struct.field('coding').list.get(0).struct.field('system').alias('code_system'),
            pl.col('type').list.get(0).struct.field('coding').list.get(0).struct.field('code').alias('type_code'),
            pl.col('meta').struct.field('lastUpdated').alias('lastUpdated'),
            pl.col('patient').struct.field('reference').str.split('/').list.get(1).alias('patient_id'),
            pl.lit(now).alias('extract_date')
        )
        .select(
            'id',
            'procedure_code',
            'code_system',
            'type_code',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
        )
    )
    return df_eob_procedure.to_pandas()

shape: (1_404, 7)
┌──────────────┬──────────────┬──────────────┬───────────┬────────────┬──────────────┬─────────────┐
│ id           ┆ procedure_co ┆ code_system  ┆ type_code ┆ patient_id ┆ lastUpdated  ┆ filename    │
│ ---          ┆ de           ┆ ---          ┆ ---       ┆ ---        ┆ ---          ┆ ---         │
│ str          ┆ ---          ┆ str          ┆ str       ┆ str        ┆ datetime[μs] ┆ str         │
│              ┆ str          ┆              ┆           ┆            ┆              ┆             │
╞══════════════╪══════════════╪══════════════╪═══════════╪════════════╪══════════════╪═════════════╡
│ 93248393639  ┆ 0SG10AJ      ┆ http://www.c ┆ principal ┆ 109664215  ┆ 2026-03-20   ┆ C:\BCDA_V3\ │
│              ┆              ┆ ms.gov/Medic ┆           ┆            ┆ 04:31:10.845 ┆ Data\Explan │
│              ┆              ┆ are/Co…      ┆           ┆            ┆              ┆ ationOfB…   │
│ 93248393639  ┆ 0SG1071      ┆ http://www.c ┆ other     ┆ 109664215  ┆ 2026-03-20   ┆ C:\BCDA_V3\ │
│              ┆              ┆ ms.gov/Medic ┆           ┆            ┆ 04:31:10.845 ┆ Data\Explan │
│              ┆              ┆ are/Co…      ┆           ┆            ┆              ┆ ationOfB…   │
│ 93248393639  ┆ 0SG30AJ      ┆ http://www.c ┆ other     ┆ 109664215  ┆ 2026-03-20   ┆ C:\BCDA_V3\ │
│              ┆              ┆ ms.gov/Medic ┆           ┆            ┆ 04:31:10.845 ┆ Data\Explan │
│              ┆              ┆ are/Co…      ┆           ┆            ┆              ┆ ationOfB…   │
│ 93248393639  ┆ 0QB33ZZ      ┆ http://www.c ┆ other     ┆ 109664215  ┆ 2026-03-20   ┆ C:\BCDA_V3\ │
│              ┆              ┆ ms.gov/Medic ┆           ┆            ┆ 04:31:10.845 ┆ Data\Explan │
│              ┆              ┆ are/Co…      ┆           ┆            ┆              ┆ ationOfB…   │
│ 93248393639  ┆ 30233N1      ┆ http://www.c ┆ other     ┆ 109664215  ┆ 2026-03-20   ┆ C:\BCDA_V3\ │
│              ┆              ┆ ms.gov/Medic ┆           ┆            ┆ 04:31:10.845 ┆ Data\Explan │
│              ┆              ┆ are/Co…      ┆           ┆            ┆              ┆ ationOfB…   │
│ …            ┆ …            ┆ …            ┆ …         ┆ …          ┆ …            ┆ …           │
│ 100638497985 ┆ 0D7G8ZZ      ┆ http://www.c ┆ principal ┆ 152421027  ┆ 2026-06-23   ┆ C:\BCDA_V3\ │
│ 7            ┆              ┆ ms.gov/Medic ┆           ┆            ┆ 01:55:18.077 ┆ Data\Explan │
│              ┆              ┆ are/Co…      ┆           ┆            ┆              ┆ ationOfB…   │
│ 100638497985 ┆ 0D7F8ZZ      ┆ http://www.c ┆ other     ┆ 152421027  ┆ 2026-06-23   ┆ C:\BCDA_V3\ │
│ 7            ┆              ┆ ms.gov/Medic ┆           ┆            ┆ 01:55:18.077 ┆ Data\Explan │
│              ┆              ┆ are/Co…      ┆           ┆            ┆              ┆ ationOfB…   │
│ 100638497985 ┆ 0DBG8ZX      ┆ http://www.c ┆ other     ┆ 152421027  ┆ 2026-06-23   ┆ C:\BCDA_V3\ │
│ 7            ┆              ┆ ms.gov/Medic ┆           ┆            ┆ 01:55:18.077 ┆ Data\Explan │
│              ┆              ┆ are/Co…      ┆           ┆            ┆              ┆ ationOfB…   │
│ 100633798231 ┆ 0DTN0ZZ      ┆ http://www.c ┆ principal ┆ 145627661  ┆ 2026-06-09   ┆ C:\BCDA_V3\ │
│ 8            ┆              ┆ ms.gov/Medic ┆           ┆            ┆ 00:54:45.963 ┆ Data\Explan │
│              ┆              ┆ are/Co…      ┆           ┆            ┆              ┆ ationOfB…   │
│ 100633798231 ┆ 0DNN0ZZ      ┆ http://www.c ┆ other     ┆ 145627661  ┆ 2026-06-09   ┆ C:\BCDA_V3\ │
│ 8            ┆              ┆ ms.gov/Medic ┆           ┆            ┆ 00:54:45.963 ┆ Data\Explan │
│              ┆              ┆ are/Co…      ┆           ┆            ┆              ┆ ationOfB…   │
└──────────────┴──────────────┴──────────────┴───────────┴────────────┴──────────────┴─────────────┘

In [ ]:
def process_eob_total(df_eob: pl.DataFrame):
    
    def safe_expr(df, source_col, expr, alias):
        if source_col in df.columns:
            return expr.alias(alias)
        return pl.lit(None).alias(alias)
    
    column_names = [
            'id',
            'total_amount',
            'category_code',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
    ]
    
    df_eob_total = (
        df_eob
        .filter(pl.col('total').is_not_null())
        .select(
            'id',
            'total',
            'patient',
            'meta',
            'filename'
        )
        .pipe(flatten, 'total')
        .with_columns(
            pl.lit(now).alias('extract_date')
        )
    )
    
    expres = [
        safe_expr(
            df_eob_total,
            'amount',
            pl.col('amount').struct.field('value'),
            'total_amount'
        ),
        safe_expr(
            df_eob_total,
            'patient',
            pl.col('patient').struct.field('reference').str.split('/').list.get(1),
            'patient_id'
        ),
        safe_expr(
            df_eob_total,
            'meta',
            pl.col('meta').struct.field('lastUpdated'),
            'lastUpdated'
        ),
        safe_expr(
            df_eob_total,
            'category',
            pl.col('category').struct.field('coding').list.get(1).struct.field('display'),
            'category_code'
        ),
    ]
    
    df_eob_total = (
        df_eob_total
        .with_columns(expres)
        .select(column_names)
    )
    
    return df_eob_total.to_pandas()

process_eob_total(df_eob)

,id,total_amount,category_code,patient_id,lastUpdated,filename,extract_date
0,1004324545686,109.40,CLM_ALOWD_CHRG_AMT,176077134,2026-03-08 09:36:25.384,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
1,1004324545686,359.00,CLM_SBMT_CHRG_AMT,176077134,2026-03-08 09:36:25.384,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
2,1004324545686,0.00,CLM_BENE_PMT_AMT,176077134,2026-03-08 09:36:25.384,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
3,1004324545686,0.00,CLM_PRVDR_PMT_AMT,176077134,2026-03-08 09:36:25.384,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
4,1004324545686,109.40,CLM_MDCR_DDCTBL_AMT,176077134,2026-03-08 09:36:25.384,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
...,...,...,...,...,...,...,...
971382,1006359631211,66.99,CLM_ALOWD_CHRG_AMT,164660944,2026-06-16 02:21:57.152,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19
971383,1006359631211,488.00,CLM_SBMT_CHRG_AMT,164660944,2026-06-16 02:21:57.152,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19
971384,1006359631211,0.00,CLM_BENE_PMT_AMT,164660944,2026-06-16 02:21:57.152,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19
971385,1006359631211,52.95,CLM_PRVDR_PMT_AMT,164660944,2026-06-16 02:21:57.152,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19
971386,1006359631211,0.00,CLM_MDCR_DDCTBL_AMT,164660944,2026-06-16 02:21:57.152,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19

In [ ]:
def process_eob_total(df_eob: pl.DataFrame):
    df_eob_total = (
        df_eob
        .filter(pl.col('total').is_not_null())
        .select(
            'id',
            'total',
            'patient',
            'meta',
            'filename'
        )
        .pipe(flatten, 'total')
        .with_columns(
            pl.col('amount').struct.field('value').alias('total_amount'),
            pl.col('patient').struct.field('reference').str.split('/').list.get(1).alias('patient_id'),
            pl.col('meta').struct.field('lastUpdated').alias('lastUpdated'),
            pl.col('category').struct.field('coding').list.get(1).struct.field('code').alias('category_code'),
            pl.lit(now).alias('extract_date')
        )
        .select(
            'id',
            'total_amount',
            'category_code',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
        )
    )
    return df_eob_total.to_pandas()

shape: (971_387, 6)
┌───────────────┬──────────────┬──────────────────┬────────────┬─────────────────┬─────────────────┐
│ id            ┆ total_amount ┆ category_code    ┆ patient_id ┆ lastUpdated     ┆ filename        │
│ ---           ┆ ---          ┆ ---              ┆ ---        ┆ ---             ┆ ---             │
│ str           ┆ f64          ┆ str              ┆ str        ┆ datetime[μs]    ┆ str             │
╞═══════════════╪══════════════╪══════════════════╪════════════╪═════════════════╪═════════════════╡
│ 1004324545686 ┆ 109.4        ┆ CLM_ALOWD_CHRG_A ┆ 176077134  ┆ 2026-03-08      ┆ C:\BCDA_V3\Data │
│               ┆              ┆ MT               ┆            ┆ 09:36:25.384    ┆ \ExplanationOfB │
│               ┆              ┆                  ┆            ┆                 ┆ …               │
│ 1004324545686 ┆ 359.0        ┆ CLM_SBMT_CHRG_AM ┆ 176077134  ┆ 2026-03-08      ┆ C:\BCDA_V3\Data │
│               ┆              ┆ T                ┆            ┆ 09:36:25.384    ┆ \ExplanationOfB │
│               ┆              ┆                  ┆            ┆                 ┆ …               │
│ 1004324545686 ┆ 0.0          ┆ CLM_BENE_PMT_AMT ┆ 176077134  ┆ 2026-03-08      ┆ C:\BCDA_V3\Data │
│               ┆              ┆                  ┆            ┆ 09:36:25.384    ┆ \ExplanationOfB │
│               ┆              ┆                  ┆            ┆                 ┆ …               │
│ 1004324545686 ┆ 0.0          ┆ CLM_PRVDR_PMT_AM ┆ 176077134  ┆ 2026-03-08      ┆ C:\BCDA_V3\Data │
│               ┆              ┆ T                ┆            ┆ 09:36:25.384    ┆ \ExplanationOfB │
│               ┆              ┆                  ┆            ┆                 ┆ …               │
│ 1004324545686 ┆ 109.4        ┆ CLM_MDCR_DDCTBL_ ┆ 176077134  ┆ 2026-03-08      ┆ C:\BCDA_V3\Data │
│               ┆              ┆ AMT              ┆            ┆ 09:36:25.384    ┆ \ExplanationOfB │
│               ┆              ┆                  ┆            ┆                 ┆ …               │
│ …             ┆ …            ┆ …                ┆ …          ┆ …               ┆ …               │
│ 1006359631211 ┆ 66.99        ┆ CLM_ALOWD_CHRG_A ┆ 164660944  ┆ 2026-06-16      ┆ C:\BCDA_V3\Data │
│               ┆              ┆ MT               ┆            ┆ 02:21:57.152    ┆ \ExplanationOfB │
│               ┆              ┆                  ┆            ┆                 ┆ …               │
│ 1006359631211 ┆ 488.0        ┆ CLM_SBMT_CHRG_AM ┆ 164660944  ┆ 2026-06-16      ┆ C:\BCDA_V3\Data │
│               ┆              ┆ T                ┆            ┆ 02:21:57.152    ┆ \ExplanationOfB │
│               ┆              ┆                  ┆            ┆                 ┆ …               │
│ 1006359631211 ┆ 0.0          ┆ CLM_BENE_PMT_AMT ┆ 164660944  ┆ 2026-06-16      ┆ C:\BCDA_V3\Data │
│               ┆              ┆                  ┆            ┆ 02:21:57.152    ┆ \ExplanationOfB │
│               ┆              ┆                  ┆            ┆                 ┆ …               │
│ 1006359631211 ┆ 52.95        ┆ CLM_PRVDR_PMT_AM ┆ 164660944  ┆ 2026-06-16      ┆ C:\BCDA_V3\Data │
│               ┆              ┆ T                ┆            ┆ 02:21:57.152    ┆ \ExplanationOfB │
│               ┆              ┆                  ┆            ┆                 ┆ …               │
│ 1006359631211 ┆ 0.0          ┆ CLM_MDCR_DDCTBL_ ┆ 164660944  ┆ 2026-06-16      ┆ C:\BCDA_V3\Data │
│               ┆              ┆ AMT              ┆            ┆ 02:21:57.152    ┆ \ExplanationOfB │
│               ┆              ┆                  ┆            ┆                 ┆ …               │
└───────────────┴──────────────┴──────────────────┴────────────┴─────────────────┴─────────────────┘

In [38]:
from datetime import datetime
MIN_SQL_DATE = datetime(1753, 1, 1)

df_eob_item = (
    df_eob
    .filter(pl.col('item').is_not_null())
    .select(
        'id',
        'item',
        'patient',
        'meta',
        'filename'
    )
    .explode('item')
    .unnest('item')
    .with_columns(
        pl.col('productOrService').struct.field('coding').list.get(0).struct.field('code').alias('product_service_code'),
        pl.col('productOrService').struct.field('coding').list.get(0).struct.field('system').str.split('/').list.get(-1).alias('product_service_system'),
        pl.col('quantity').struct.field('value').alias('quantity_value'),
        pl.col('patient').struct.field('reference').str.split('/').list.get(1).alias('patient_id'),
        pl.col('meta').struct.field('lastUpdated').alias('lastUpdated'),
        pl.col('revenue').struct.field('coding').list.get(0).struct.field('code').alias('revenue_code'),
        pl.col('revenue').struct.field('coding').list.get(0).struct.field('display').alias('revenue_display'),
        pl.col('servicedPeriod').struct.field('start').alias('service_start'),
        pl.col('servicedPeriod').struct.field('end').alias('service_end'),
        pl.col('locationCodeableConcept').struct.field('coding').list.get(0).struct.field('code').alias('location_code'),
        pl.col('locationCodeableConcept').struct.field('coding').list.get(0).struct.field('display').alias('location_display'),
        pl.col('diagnosisSequence').list.get(0).alias('diagnosisSequence'),
        pl.col('informationSequence').list.get(0).alias('informationSequence'),
        pl.col('modifier').list.get(0).struct.field('coding').list.get(0).struct.field('code').alias('modifier'),
        pl.when(pl.col('servicedDate') < MIN_SQL_DATE)
        .then(None)
        .otherwise(pl.col('servicedDate'))
        .alias('servicedDate')
    )
    .select(
        'id',
        'sequence',
        'diagnosisSequence',
        'informationSequence',
        'location_code',
        'location_display',
        'product_service_code',
        'modifier',
        'product_service_system',
        'quantity_value',
        'revenue_code',
        'revenue_display',
        'service_start',
        'service_end',
        'servicedDate',
        'patient_id',
        'lastUpdated',
        'filename'
    )
)
df_eob_item

shape: (488_217, 18)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id        ┆ sequence ┆ diagnosis ┆ informati ┆ … ┆ servicedD ┆ patient_i ┆ lastUpdat ┆ filename  │
│ ---       ┆ ---      ┆ Sequence  ┆ onSequenc ┆   ┆ ate       ┆ d         ┆ ed        ┆ ---       │
│ str       ┆ i64      ┆ ---       ┆ e         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str       │
│           ┆          ┆ i64       ┆ ---       ┆   ┆ date      ┆ str       ┆ datetime[ ┆           │
│           ┆          ┆           ┆ i64       ┆   ┆           ┆           ┆ μs]       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100432454 ┆ 1        ┆ 1         ┆ 3         ┆ … ┆ null      ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 5686      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 8 09:36:2 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 5.384     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100435782 ┆ 1        ┆ 1         ┆ 3         ┆ … ┆ null      ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 1502      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 8 11:46:0 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 0.861     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100435782 ┆ 1        ┆ null      ┆ null      ┆ … ┆ null      ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 2988      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 7 10:43:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 5.187     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100435782 ┆ 2        ┆ null      ┆ null      ┆ … ┆ null      ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 2988      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 7 10:43:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 5.187     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100437706 ┆ 1        ┆ 1         ┆ 3         ┆ … ┆ null      ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 5539      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 9 01:19:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 6.899     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 100640897 ┆ 2        ┆ 2         ┆ 4         ┆ … ┆ null      ┆ 99908141  ┆ 2026-06-3 ┆ C:\BCDA_V │
│ 0910      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 0 01:49:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 6.241     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100633797 ┆ 1        ┆ 1         ┆ 3         ┆ … ┆ null      ┆ 164660944 ┆ 2026-06-0 ┆ C:\BCDA_V │
│ 1749      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 9 01:21:0 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 0.072     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100633797 ┆ 1        ┆ null      ┆ null      ┆ … ┆ null      ┆ 164660944 ┆ 2026-06-0 ┆ C:\BCDA_V │
│ 2436      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 9 01:01:4 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 3.513     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100633797 ┆ 2        ┆ null      ┆ null      ┆ … ┆ null      ┆ 164660944 ┆ 2026-06-0 ┆ C:\BCDA_V │
│ 2436      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 9 01:01:4 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 3.513     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100635963 ┆ 1        ┆ 1         ┆ 3         ┆ … ┆ null      ┆ 164660944 ┆ 2026-06-1 ┆ C:\BCDA_V │
│ 1211      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 7.152     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
from datetime import datetime

now = datetime.now().strftime('%d/%m/%Y %H:%M:%S')

def process_eob_item(df_eob: pl.DataFrame):
    
    
    def safe_expr(df, source_col, expr, alias):
        if source_col in df.columns:
            return expr.alias(alias)
        return pl.lit(None).alias(alias)
    

    column_names = [
            'id',
            'sequence',
            'diagnosisSequence',
            'informationSequence',
            'location_code',
            'location_display',
            'product_service_code',
            'modifier',
            'product_service_system',
            'quantity_value',
            'revenue_code',
            'revenue_display',
            'service_start',
            'service_end',
            'servicedDate',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
    ]
    

    
    df_eob_item = (
        df_eob
        .filter(pl.col('item').is_not_null())
        .select(
            'id',
            'item',
            'patient',
            'meta',
            'filename'
        )
        .pipe(flatten, 'item')
        .with_columns(
            pl.lit(now).alias('extract_date')
        )
    )
    
        
    expr = [
        safe_expr(
            df_eob_item,
            'productOrService',
            pl.col('productOrService').struct.field('coding').list.get(0).struct.field('code'),
            'product_service_code'
        ),
        safe_expr(
            df_eob_item,
            'productOrService',
            pl.col('productOrService').struct.field('coding').list.get(0).struct.field('system').str.split('/').list.get(-1),
            'product_service_system'
        ),   
        safe_expr(
            df_eob_item,
            'quantity',
            pl.col('quantity').struct.field('value'),
            'quantity_value'
        ),
        safe_expr(
            df_eob_item,
            'patient',
            pl.col('patient').struct.field('reference').str.split('/').list.get(1),
            'patient_id'
        ),
        safe_expr(
            df_eob_item,
            'meta',
            pl.col('meta').struct.field('lastUpdated'),
            'lastUpdated'
        ),
        safe_expr(
            df_eob_item,
            'revenue',
            pl.col('revenue').struct.field('coding').list.get(0).struct.field('code'),
            'revenue_code'
        ),
        safe_expr(
            df_eob_item,
            'revenue',
            pl.col('revenue').struct.field('coding').list.get(0).struct.field('display'),
            'revenue_display'
        ),   
        safe_expr(
            df_eob_item,
            'servicedPeriod',
            pl.col('servicedPeriod').struct.field('start'),
            'service_start'
        ),
        safe_expr(
            df_eob_item,
            'servicedPeriod',
            pl.col('servicedPeriod').struct.field('end'),
            'service_end'
        ),
        safe_expr(
            df_eob_item,
            'locationCodeableConcept',
            pl.col('locationCodeableConcept').struct.field('coding').list.get(0).struct.field('code'),
            'location_code'
        ),
        safe_expr(
            df_eob_item,
            'locationCodeableConcept',
            pl.col('locationCodeableConcept').struct.field('coding').list.get(0).struct.field('display'),
            'location_display'
        ),
        safe_expr(
            df_eob_item,
            'diagnosisSequence',
            pl.col('diagnosisSequence').list.get(0),
            'diagnosisSequence'
        ),   
        safe_expr(
            df_eob_item,
            'informationSequence',
            pl.col('informationSequence').list.get(0),
            'informationSequence'
        ),
        safe_expr(
            df_eob_item,
            'modifier',
            pl.col('modifier').list.get(0).struct.field('coding').list.get(0).struct.field('code'),
            'modifier'
        ),
        safe_expr(
            df_eob_item,
            'servicedDate',
            pl.when(pl.col('servicedDate') < MIN_SQL_DATE).then(None).otherwise(pl.col('servicedDate')),
            'servicedDate'
        )
    ]
    df_eob_item = (
        df_eob_item
        .with_columns(expr)
        .select(column_names)
    )
        
    return df_eob_item.to_pandas()



process_eob_item(df_eob)

,id,sequence,diagnosisSequence,informationSequence,location_code,location_display,product_service_code,modifier,product_service_system,quantity_value,revenue_code,revenue_display,service_start,service_end,servicedDate,patient_id,lastUpdated,filename,extract_date
0,1004324545686,1,1.0,3.0,10,Telehealth Provided in Patient’s Home,99214,None,cpt,1.0,None,None,2024-10-14,2024-10-14,NaT,176077134,2026-03-08 09:36:25.384,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 07:59:47
1,1004357821502,1,1.0,3.0,10,Telehealth Provided in Patient’s Home,99213,95,cpt,1.0,None,None,2024-09-05,2024-09-05,NaT,176077134,2026-03-08 11:46:00.861,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 07:59:47
2,1004357822988,1,NaN,NaN,None,None,Q3014,None,HCPCSReleaseCodeSets,1.0,0780,TELEMEDICINE - GENERAL CLASSIFICATION,2024-09-05,2024-09-05,NaT,176077134,2026-03-07 10:43:55.187,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 07:59:47
3,1004357822988,2,NaN,NaN,None,None,not-applicable,None,data-absent-reason,0.0,0001,TOTAL CHARGE,NaT,NaT,NaT,176077134,2026-03-07 10:43:55.187,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 07:59:47
4,1004377065539,1,1.0,3.0,15,Mobile Unit,93000,None,cpt,1.0,None,None,2024-09-24,2024-09-24,NaT,176077134,2026-03-09 01:19:56.899,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 07:59:47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488212,1006408970910,2,2.0,4.0,11,Office,81002,59,cpt,1.0,None,None,2026-05-26,2026-05-26,NaT,99908141,2026-06-30 01:49:56.241,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 07:59:47
488213,1006337971749,1,1.0,3.0,11,Office,99214,None,cpt,1.0,None,None,2026-05-27,2026-05-27,NaT,164660944,2026-06-09 01:21:00.072,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 07:59:47
488214,1006337972436,1,NaN,NaN,None,None,72141,TC,cpt,1.0,0610,MAGNETIC RESONANCE TECHNOLOGY (MRT) - GENERAL ...,2026-05-27,2026-05-27,NaT,164660944,2026-06-09 01:01:43.513,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 07:59:47
488215,1006337972436,2,NaN,NaN,None,None,not-applicable,None,data-absent-reason,0.0,0001,TOTAL CHARGE,NaT,NaT,NaT,164660944,2026-06-09 01:01:43.513,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 07:59:47
488216,1006359631211,1,1.0,3.0,22,On Campus-Outpatient Hospital,72141,26,cpt,1.0,None,None,2026-05-27,2026-05-27,NaT,164660944,2026-06-16 02:21:57.152,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 07:59:47

In [ ]:
def process_eob_adjudication(df_eob: pl.DataFrame):
    def safe_expr(df, source_col, expr, alias):
        if source_col in df.columns:
            return expr.alias(alias)
        return pl.lit(None).alias(alias)

In [94]:
def process_eob_adjudication(df_eob: pl.DataFrame):
    
    def safe_expr(df, source_col, expr, alias):
        if source_col in df.columns:
            return expr.alias(alias)
        return pl.lit(None).alias(alias)
    
    column_names = [
        'claim_id',
        'category_display',
        'reason_display',
        'amount',
        'value',
        'lastUpdated',
        'filename'
    ]

    df_eob_adjudication = (
        df_eob
        .filter(pl.col('adjudication').is_not_null())
        .select(
            'id',
            'adjudication',
            'meta',
            'filename'
        )
        .explode('adjudication')
        .unnest('adjudication')
        .with_columns(
            pl.col('id').alias('claim_id'),
            pl.col('meta').struct.field('lastUpdated'),
            pl.col('filename').str.split('\\').list.get(-1).alias('filename')
        )
    )
    expres = [
        safe_expr(
            df_eob_adjudication,
            'category',
            pl.col('category').struct.field('coding').list.get(0).struct.field('display'),
            'category_display'
        ),
        safe_expr(
            df_eob_adjudication,
            'reason',
            pl.col('reason').struct.field('coding').list.get(0).struct.field('display'),
            'reason_display'
        ),
        safe_expr(
            df_eob_adjudication,
            'amount',
            pl.col('amount').struct.field('value'),
            'amount'
        )
    ]
    df_eob_adjudication = (
        df_eob_adjudication
        .with_columns(expres)
        .select(column_names)
    )
    return df_eob_adjudication#.to_pandas()

adjudication = process_eob_adjudication(df_eob)
adjudication.filter((pl.col('value').is_not_null()) & (pl.col('value')> 0))

shape: (50, 7)
┌───────────────┬────────────────┬────────────────┬────────┬───────┬───────────────┬───────────────┐
│ claim_id      ┆ category_displ ┆ reason_display ┆ amount ┆ value ┆ lastUpdated   ┆ filename      │
│ ---           ┆ ay             ┆ ---            ┆ ---    ┆ ---   ┆ ---           ┆ ---           │
│ str           ┆ ---            ┆ str            ┆ f64    ┆ f64   ┆ datetime[μs]  ┆ str           │
│               ┆ str            ┆                ┆        ┆       ┆               ┆               │
╞═══════════════╪════════════════╪════════════════╪════════╪═══════╪═══════════════╪═══════════════╡
│ 1002007650463 ┆ PPS DRG Weight ┆ null           ┆ null   ┆ 3.36  ┆ 2026-04-30    ┆ ExplanationOf │
│               ┆ Number         ┆                ┆        ┆       ┆ 18:28:59.785  ┆ Benefit_v3_00 │
│               ┆                ┆                ┆        ┆       ┆               ┆ 42_2…         │
│ 1002007650463 ┆ Claim Medicare ┆ null           ┆ null   ┆ 1.0   ┆ 2026-04-30    ┆ ExplanationOf │
│               ┆ Utilization    ┆                ┆        ┆       ┆ 18:28:59.785  ┆ Benefit_v3_00 │
│               ┆ Day…           ┆                ┆        ┆       ┆               ┆ 42_2…         │
│ 1006310511766 ┆ PPS DRG Weight ┆ null           ┆ null   ┆ 1.94  ┆ 2026-06-02    ┆ ExplanationOf │
│               ┆ Number         ┆                ┆        ┆       ┆ 07:00:41.781  ┆ Benefit_v3_00 │
│               ┆                ┆                ┆        ┆       ┆               ┆ 42_2…         │
│ 1006310511766 ┆ Claim Medicare ┆ null           ┆ null   ┆ 1.0   ┆ 2026-06-02    ┆ ExplanationOf │
│               ┆ Utilization    ┆                ┆        ┆       ┆ 07:00:41.781  ┆ Benefit_v3_00 │
│               ┆ Day…           ┆                ┆        ┆       ┆               ┆ 42_2…         │
│ 1002435540236 ┆ PPS DRG Weight ┆ null           ┆ null   ┆ 2.35  ┆ 2026-04-30    ┆ ExplanationOf │
│               ┆ Number         ┆                ┆        ┆       ┆ 18:28:59.785  ┆ Benefit_v3_00 │
│               ┆                ┆                ┆        ┆       ┆               ┆ 42_2…         │
│ …             ┆ …              ┆ …              ┆ …      ┆ …     ┆ …             ┆ …             │
│ 1003034087566 ┆ Claim Medicare ┆ null           ┆ null   ┆ 7.0   ┆ 2026-04-30    ┆ ExplanationOf │
│               ┆ Utilization    ┆                ┆        ┆       ┆ 18:28:59.785  ┆ Benefit_v3_00 │
│               ┆ Day…           ┆                ┆        ┆       ┆               ┆ 42_2…         │
│ 1006385631479 ┆ PPS DRG Weight ┆ null           ┆ null   ┆ 1.94  ┆ 2026-06-23    ┆ ExplanationOf │
│               ┆ Number         ┆                ┆        ┆       ┆ 01:55:19.886  ┆ Benefit_v3_00 │
│               ┆                ┆                ┆        ┆       ┆               ┆ 42_2…         │
│ 1006385631479 ┆ Claim Medicare ┆ null           ┆ null   ┆ 1.0   ┆ 2026-06-23    ┆ ExplanationOf │
│               ┆ Utilization    ┆                ┆        ┆       ┆ 01:55:19.886  ┆ Benefit_v3_00 │
│               ┆ Day…           ┆                ┆        ┆       ┆               ┆ 42_2…         │
│ 1002503708721 ┆ PPS DRG Weight ┆ null           ┆ null   ┆ 1.9   ┆ 2026-04-30    ┆ ExplanationOf │
│               ┆ Number         ┆                ┆        ┆       ┆ 18:28:59.785  ┆ Benefit_v3_00 │
│               ┆                ┆                ┆        ┆       ┆               ┆ 42_2…         │
│ 1002503708721 ┆ Claim Medicare ┆ null           ┆ null   ┆ 2.0   ┆ 2026-04-30    ┆ ExplanationOf │
│               ┆ Utilization    ┆                ┆        ┆       ┆ 18:28:59.785  ┆ Benefit_v3_00 │
│               ┆ Day…           ┆                ┆        ┆       ┆               ┆ 42_2…         │
└───────────────┴────────────────┴────────────────┴────────┴───────┴───────────────┴───────────────┘

In [ ]:
def process_eob_item_adjudication(df_eob: pl.DataFrame):
    
    def safe_expr(df, source_col, expr, alias):
        if source_col in df.columns:
            return expr.alias(alias)
        return pl.lit(None).alias(alias)
    
    column_names = [
            'id',
            'sequence',
            'adjudication_amount',
            'adjudication_category_display',
            'adjudication_reason_display',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
    ]
    
    df_eob_item_adjudication = (
        df_eob
        .filter(pl.col('item').is_not_null())
        .select(
            'id',
            'item',
            'patient',
            'meta',
            'filename'
        )
        .pipe(flatten, 'item')
        .select(
            'id',
            'sequence',
            'adjudication',
            'patient',
            'meta',
            'filename'
        )
        .filter(pl.col('adjudication').is_not_null())
        .pipe(flatten, 'adjudication')
        .with_columns(
            pl.lit(now).alias('extract_date')
        )
    )
    
    expres = [
        safe_expr(
            df_eob_item_adjudication,
            'amount',
            pl.col('amount').struct.field('value'),
            'adjudication_amount'
        ),
        safe_expr(
            df_eob_item_adjudication,
            'patient',
            pl.col('patient').struct.field('reference').str.split('/').list.get(1),
            'patient_id'
        ),
        safe_expr(
            df_eob_item_adjudication,
            'meta',
            pl.col('meta').struct.field('lastUpdated'),
            'lastUpdated'
        ),
        safe_expr(
            df_eob_item_adjudication,
            'category',
            pl.col('category').struct.field('coding').list.get(0).struct.field('display'),
            'adjudication_category_display'
        ),
        safe_expr(
            df_eob_item_adjudication,
            'reason',
            pl.col('reason').struct.field('coding').list.get(0).struct.field('display'),
            'adjudication_reason_display'
        ),
    ]
    
    df_eob_item_adjudication = (
        df_eob_item_adjudication
        .with_columns(expres)
        .select(column_names)
    )
    
    return df_eob_item_adjudication

adjudication = process_eob_item_adjudication(df_eob)

ColumnNotFoundError: unable to find column "value"; valid columns: ["id", "sequence", "amount", "category", "reason", "patient", "meta", "filename", "extract_date", "adjudication_amount", "patient_id", "lastUpdated", "adjudication_category_display", "adjudication_reason_display"]

In [ ]:
adjudication

In [60]:
adjudication.filter(pl.col('id') == '1001369071601').show(limit=None)

id,sequence,adjudication_amount,adjudication_category_display,adjudication_reason_display,patient_id,lastUpdated,filename,extract_date
str,i64,f64,str,str,str,datetime[μs],str,str
"""1001369071601""",1,0.0,"""Deductible""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,0.0,"""Blood Deductible Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,0.0,"""Paid to patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,0.0,"""Paid by patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,0.0,"""Noncovered""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,0.0,"""Paid to provider""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,0.0,"""Benefit Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,5828.0,"""Submitted Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,0.0,"""Revenue Center Coinsurance/Wag…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,0.0,"""Revenue Center Reduced Coinsur…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,0.0,"""Revenue Center Rate Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,0.0,"""Add On Payment Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",1,0.0,"""Transitional Drug Add-On Payme…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Deductible""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Blood Deductible Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Paid to patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Paid by patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Noncovered""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Paid to provider""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Benefit Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,7412.07,"""Submitted Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Revenue Center Coinsurance/Wag…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Revenue Center Reduced Coinsur…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Revenue Center Rate Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Add On Payment Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",2,0.0,"""Transitional Drug Add-On Payme…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Deductible""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Blood Deductible Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Paid to patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Paid by patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Noncovered""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Paid to provider""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Benefit Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,854.79,"""Submitted Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Revenue Center Coinsurance/Wag…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Revenue Center Reduced Coinsur…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Revenue Center Rate Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Add On Payment Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",3,0.0,"""Transitional Drug Add-On Payme…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Deductible""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Blood Deductible Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Paid to patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Paid by patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Noncovered""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Paid to provider""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Benefit Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,4455.36,"""Submitted Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Revenue Center Coinsurance/Wag…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Revenue Center Reduced Coinsur…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Revenue Center Rate Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Add On Payment Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",4,0.0,"""Transitional Drug Add-On Payme…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Deductible""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Blood Deductible Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Paid to patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Paid by patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Noncovered""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Paid to provider""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Benefit Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,207.96,"""Submitted Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Revenue Center Coinsurance/Wag…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Revenue Center Reduced Coinsur…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Revenue Center Rate Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Add On Payment Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",5,0.0,"""Transitional Drug Add-On Payme…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Deductible""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Blood Deductible Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Paid to patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Paid by patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Noncovered""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Paid to provider""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Benefit Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,1602.0,"""Submitted Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Revenue Center Coinsurance/Wag…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Revenue Center Reduced Coinsur…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Revenue Center Rate Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Add On Payment Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",6,0.0,"""Transitional Drug Add-On Payme…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Deductible""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Blood Deductible Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Paid to patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Paid by patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Noncovered""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Paid to provider""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Benefit Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,3595.0,"""Submitted Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Revenue Center Coinsurance/Wag…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Revenue Center Reduced Coinsur…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Revenue Center Rate Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Add On Payment Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",7,0.0,"""Transitional Drug Add-On Payme…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Deductible""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Blood Deductible Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Paid to patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Paid by patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Noncovered""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Paid to provider""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Benefit Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,666.0,"""Submitted Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Revenue Center Coinsurance/Wag…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Revenue Center Reduced Coinsur…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Prior payer paid""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Revenue Center Rate Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Add On Payment Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",8,0.0,"""Transitional Drug Add-On Payme…",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",9,0.0,"""Deductible""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",9,0.0,"""Blood Deductible Amount""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",9,0.0,"""Paid to patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""
"""1001369071601""",9,0.0,"""Paid by patient""",null,"""163781595""",2026-04-30 18:28:59.785,"""C:\BCDA_V3\Data\ExplanationOfB…","""06/07/2026 15:49:33"""

In [ ]:
def process_eob_item_adjudication(df_eob: pl.DataFrame):
    
    df_eob_item_adjudication = (
        df_eob
        .filter(pl.col('item').is_not_null())
        .select(
            'id',
            'item',
            'patient',
            'meta',
            'filename'
        )
        .pipe(flatten, 'item')
        .select(
            'id',
            'sequence',
            'adjudication',
            'patient',
            'meta',
            'filename'
        )
        .filter(pl.col('adjudication').is_not_null())
        .pipe(flatten, 'adjudication')
        .with_columns(
            pl.col('amount').struct.field('value').alias('adjudication_amount'),
            pl.col('patient').struct.field('reference').str.split('/').list.get(1).alias('patient_id'),
            pl.col('meta').struct.field('lastUpdated').alias('lastUpdated'),
            pl.col('category').struct.field('coding').list.get(0).struct.field('display').alias('adjudication_category_display'),
            pl.col('reason').struct.field('coding').list.get(0).struct.field('display').alias('adjudication_reason_display'),
            pl.lit(now).alias('extract_date')
        )
        .select(
            'id',
            'sequence',
            'adjudication_amount',
            'adjudication_category_display',
            'adjudication_reason_display',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
        )
    )
    return df_eob_item_adjudication.to_pandas()

shape: (5_756, 6)
┌───────────────┬────────────────────┬────────────────┬────────┬───────────────┬───────────────────┐
│ claim_id      ┆ category_display   ┆ reason_display ┆ amount ┆ lastUpdated   ┆ filename          │
│ ---           ┆ ---                ┆ ---            ┆ ---    ┆ ---           ┆ ---               │
│ str           ┆ str                ┆ str            ┆ f64    ┆ datetime[μs]  ┆ str               │
╞═══════════════╪════════════════════╪════════════════╪════════╪═══════════════╪═══════════════════╡
│ 511135542926  ┆ Benefit Payment    ┆ In Network     ┆ null   ┆ 2026-03-31    ┆ ExplanationOfBene │
│               ┆ Status             ┆                ┆        ┆ 18:39:05.937  ┆ fit_v3_0032_2…    │
│ 511135559726  ┆ Benefit Payment    ┆ In Network     ┆ null   ┆ 2026-04-13    ┆ ExplanationOfBene │
│               ┆ Status             ┆                ┆        ┆ 19:10:23.399  ┆ fit_v3_0032_2…    │
│ 511135559727  ┆ Benefit Payment    ┆ In Network     ┆ null   ┆ 2026-04-13    ┆ ExplanationOfBene │
│               ┆ Status             ┆                ┆        ┆ 19:10:23.399  ┆ fit_v3_0032_2…    │
│ 511251162334  ┆ Benefit Payment    ┆ In Network     ┆ null   ┆ 2026-04-13    ┆ ExplanationOfBene │
│               ┆ Status             ┆                ┆        ┆ 19:10:23.399  ┆ fit_v3_0032_2…    │
│ 511251162335  ┆ Benefit Payment    ┆ In Network     ┆ null   ┆ 2026-04-13    ┆ ExplanationOfBene │
│               ┆ Status             ┆                ┆        ┆ 19:10:23.399  ┆ fit_v3_0032_2…    │
│ …             ┆ …                  ┆ …              ┆ …      ┆ …             ┆ …                 │
│ 1006359630822 ┆ Blood Noncovered   ┆ null           ┆ 0.0    ┆ 2026-06-16    ┆ ExplanationOfBene │
│               ┆ Charge Amount      ┆                ┆        ┆ 02:11:11.310  ┆ fit_v3_0032_2…    │
│ 1006385623798 ┆ Benefit Payment    ┆ Other          ┆ null   ┆ 2026-06-23    ┆ ExplanationOfBene │
│               ┆ Status             ┆                ┆        ┆ 02:26:25.804  ┆ fit_v3_0032_2…    │
│ 1006385623798 ┆ Primary Payer Paid ┆ null           ┆ 0.0    ┆ 2026-06-23    ┆ ExplanationOfBene │
│               ┆ Amount             ┆                ┆        ┆ 02:26:25.804  ┆ fit_v3_0032_2…    │
│ 1006385624455 ┆ Benefit Payment    ┆ Other          ┆ null   ┆ 2026-06-23    ┆ ExplanationOfBene │
│               ┆ Status             ┆                ┆        ┆ 02:26:25.804  ┆ fit_v3_0032_2…    │
│ 1006385624455 ┆ Primary Payer Paid ┆ null           ┆ 0.0    ┆ 2026-06-23    ┆ ExplanationOfBene │
│               ┆ Amount             ┆                ┆        ┆ 02:26:25.804  ┆ fit_v3_0032_2…    │
└───────────────┴────────────────────┴────────────────┴────────┴───────────────┴───────────────────┘

In [104]:
def process_eob_item_ext(df_eob: pl.DataFrame):
    
    def safe_expr(df, source_col, expr, alias):
        if source_col in df.columns:
            return expr.alias(alias)
        return pl.lit(None).alias(alias)
    
    column_names = [
            'id',
            'sequence',
            'identifierValue',
            'valueDecimal',
            'extension_code',
            'extension_display',
            'url',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
    ]
    
    df_eob_item_ext = (
        df_eob
        .filter(pl.col('item').is_not_null())
        .select(
            'id',
            'item',
            'patient',
            'meta',
            'filename'
        )
        .pipe(flatten, 'item')
        .select(
            'id',
            'sequence',
            'extension',
            'patient',
            'meta',
            'filename'
        )
        .filter(pl.col('extension').is_not_null())
        .pipe(flatten, 'extension')
        .with_columns(
            pl.lit(now).alias('extract_date')
        )
    )
    
    expres = [
        safe_expr(
            df_eob_item_ext,
            'valueCoding',
            pl.col('valueCoding').struct.field('code'),
            'extension_code'
        ),
        safe_expr(
            df_eob_item_ext,
            'valueCoding',
            pl.col('valueCoding').struct.field('display'),
            'extension_display'
        ),
        safe_expr(
            df_eob_item_ext,
            'valueIdentifier',
            pl.col('valueIdentifier').struct.field('value'),
            'identifierValue'
        ),
        safe_expr(
            df_eob_item_ext,
            'patient',
            pl.col('patient').struct.field('reference').str.split('/').list.get(1),
            'patient_id'
        ),
        safe_expr(
            df_eob_item_ext,
            'meta',
            pl.col('meta').struct.field('lastUpdated'),
            'lastUpdated'
        )
    ]
    
    df_eob_item_ext = (
        df_eob_item_ext
        .with_columns(expres)
        .select(column_names)
    )
    
    return df_eob_item_ext

df_eob_item_ext = process_eob_item_ext(df_eob)
df_eob_item_ext.filter(pl.col('valueDecimal').is_not_null())

shape: (2_886, 11)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id        ┆ sequence ┆ identifie ┆ valueDeci ┆ … ┆ patient_i ┆ lastUpdat ┆ filename  ┆ extract_d │
│ ---       ┆ ---      ┆ rValue    ┆ mal       ┆   ┆ d         ┆ ed        ┆ ---       ┆ ate       │
│ str       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│           ┆          ┆ str       ┆ f64       ┆   ┆ str       ┆ datetime[ ┆           ┆ str       │
│           ┆          ┆           ┆           ┆   ┆           ┆ μs]       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100607594 ┆ 1        ┆ null      ┆ 0.0       ┆ … ┆ 146074456 ┆ 2026-04-3 ┆ C:\BCDA_V ┆ 06/07/202 │
│ 2385      ┆          ┆           ┆           ┆   ┆           ┆ 0 18:29:0 ┆ 3\Data\Ex ┆ 6         │
│           ┆          ┆           ┆           ┆   ┆           ┆ 0.177     ┆ planation ┆ 15:49:33  │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ OfB…      ┆           │
│ 100607594 ┆ 1        ┆ null      ┆ 1.0       ┆ … ┆ 146074456 ┆ 2026-04-3 ┆ C:\BCDA_V ┆ 06/07/202 │
│ 2385      ┆          ┆           ┆           ┆   ┆           ┆ 0 18:29:0 ┆ 3\Data\Ex ┆ 6         │
│           ┆          ┆           ┆           ┆   ┆           ┆ 0.177     ┆ planation ┆ 15:49:33  │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ OfB…      ┆           │
│ 100599208 ┆ 1        ┆ null      ┆ 0.0       ┆ … ┆ 69733319  ┆ 2026-03-3 ┆ C:\BCDA_V ┆ 06/07/202 │
│ 0409      ┆          ┆           ┆           ┆   ┆           ┆ 0 20:40:0 ┆ 3\Data\Ex ┆ 6         │
│           ┆          ┆           ┆           ┆   ┆           ┆ 5.412     ┆ planation ┆ 15:49:33  │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ OfB…      ┆           │
│ 100599208 ┆ 1        ┆ null      ┆ 1.0       ┆ … ┆ 69733319  ┆ 2026-03-3 ┆ C:\BCDA_V ┆ 06/07/202 │
│ 0409      ┆          ┆           ┆           ┆   ┆           ┆ 0 20:40:0 ┆ 3\Data\Ex ┆ 6         │
│           ┆          ┆           ┆           ┆   ┆           ┆ 5.412     ┆ planation ┆ 15:49:33  │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ OfB…      ┆           │
│ 100599208 ┆ 2        ┆ null      ┆ 0.0       ┆ … ┆ 69733319  ┆ 2026-03-3 ┆ C:\BCDA_V ┆ 06/07/202 │
│ 0409      ┆          ┆           ┆           ┆   ┆           ┆ 0 20:40:0 ┆ 3\Data\Ex ┆ 6         │
│           ┆          ┆           ┆           ┆   ┆           ┆ 5.412     ┆ planation ┆ 15:49:33  │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ OfB…      ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 100635961 ┆ 2        ┆ null      ┆ 28.0      ┆ … ┆ 138993899 ┆ 2026-06-1 ┆ C:\BCDA_V ┆ 06/07/202 │
│ 1447      ┆          ┆           ┆           ┆   ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex ┆ 6         │
│           ┆          ┆           ┆           ┆   ┆           ┆ 6.466     ┆ planation ┆ 15:49:33  │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ OfB…      ┆           │
│ 100638560 ┆ 1        ┆ null      ┆ 0.0       ┆ … ┆ 138993899 ┆ 2026-06-2 ┆ C:\BCDA_V ┆ 06/07/202 │
│ 4909      ┆          ┆           ┆           ┆   ┆           ┆ 3 02:26:1 ┆ 3\Data\Ex ┆ 6         │
│           ┆          ┆           ┆           ┆   ┆           ┆ 5.607     ┆ planation ┆ 15:49:33  │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ OfB…      ┆           │
│ 100638560 ┆ 1        ┆ null      ┆ 1.0       ┆ … ┆ 138993899 ┆ 2026-06-2 ┆ C:\BCDA_V ┆ 06/07/202 │
│ 4909      ┆          ┆           ┆           ┆   ┆           ┆ 3 02:26:1 ┆ 3\Data\Ex ┆ 6         │
│           ┆          ┆           ┆           ┆   ┆           ┆ 5.607     ┆ planation ┆ 15:49:33  │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ OfB…      ┆           │
│ 100638560 ┆ 1        ┆ null      ┆ 0.0       ┆ … ┆ 138993899 ┆ 2026-06-2 ┆ C:\BCDA_V ┆ 06/07/202 │
│ 5431      ┆          ┆           ┆           ┆   ┆           ┆ 3 02:26:1 ┆ 3\Data\Ex ┆ 6         │
│           ┆          ┆           ┆           ┆   ┆           ┆ 5.607     ┆ planation ┆ 15:49:33  │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ OfB…      ┆           │
│ 100638560 ┆ 1        ┆ null      ┆ 1.0       ┆ … ┆ 138993899 ┆ 2026-06-2 ┆ C:\BCDA_V ┆ 06/07/202 │
│ 5431      ┆          ┆           ┆           ┆   ┆           ┆ 3 02:26:1 ┆ 3\Data\Ex ┆ 6         │
│           ┆          ┆           ┆           ┆   ┆           ┆ 5.607     ┆ planation ┆ 15:49:33  │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ OfB…      ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
def process_eob_item_ext(df_eob: pl.DataFrame):
    df_eob_item_ext = (
        df_eob
        .filter(pl.col('item').is_not_null())
        .select(
            'id',
            'item',
            'patient',
            'meta',
            'filename'
        )
        .pipe(flatten, 'item')
        .select(
            'id',
            'sequence',
            'extension',
            'patient',
            'meta',
            'filename'
        )
        .filter(pl.col('extension').is_not_null())
        .pipe(flatten, 'extension')
        .with_columns(
            pl.col('valueCoding').struct.field('code').alias('extension_code'),
            pl.col('valueCoding').struct.field('display').alias('extension_display'),
            pl.col('patient').struct.field('reference').str.split('/').list.get(1).alias('patient_id'),
            pl.col('meta').struct.field('lastUpdated').alias('lastUpdated'),
            pl.lit(now).alias('extract_date')
        )
        .select(
            'id',
            'sequence',
            'extension_code',
            'extension_display',
            'url',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
        )
    )
    return df_eob_item_ext.to_pandas()

shape: (2_959_631, 8)
┌────────────┬──────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┐
│ id         ┆ sequence ┆ extension_ ┆ extension_ ┆ url        ┆ patient_i ┆ lastUpdat ┆ filename  │
│ ---        ┆ ---      ┆ code       ┆ display    ┆ ---        ┆ d         ┆ ed        ┆ ---       │
│ str        ┆ i64      ┆ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ str       │
│            ┆          ┆ str        ┆ str        ┆            ┆ str       ┆ datetime[ ┆           │
│            ┆          ┆            ┆            ┆            ┆           ┆ μs]       ┆           │
╞════════════╪══════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1004324545 ┆ 1        ┆ 1          ┆ Medical    ┆ https://bl ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 686        ┆          ┆            ┆ care       ┆ uebutton.c ┆           ┆ 8 09:36:2 ┆ 3\Data\Ex │
│            ┆          ┆            ┆            ┆ ms.gov/fhi ┆           ┆ 5.384     ┆ planation │
│            ┆          ┆            ┆            ┆ …          ┆           ┆           ┆ OfB…      │
│ 1004324545 ┆ 1        ┆ 0          ┆ 80%        ┆ https://bl ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 686        ┆          ┆            ┆            ┆ uebutton.c ┆           ┆ 8 09:36:2 ┆ 3\Data\Ex │
│            ┆          ┆            ┆            ┆ ms.gov/fhi ┆           ┆ 5.384     ┆ planation │
│            ┆          ┆            ┆            ┆ …          ┆           ┆           ┆ OfB…      │
│ 1004324545 ┆ 1        ┆ 50         ┆ NURSE PRAC ┆ https://bl ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 686        ┆          ┆            ┆ TITIONER   ┆ uebutton.c ┆           ┆ 8 09:36:2 ┆ 3\Data\Ex │
│            ┆          ┆            ┆            ┆ ms.gov/fhi ┆           ┆ 5.384     ┆ planation │
│            ┆          ┆            ┆            ┆ …          ┆           ┆           ┆ OfB…      │
│ 1004324545 ┆ 1        ┆ 0          ┆ Service    ┆ https://bl ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 686        ┆          ┆            ┆ Subject to ┆ uebutton.c ┆           ┆ 8 09:36:2 ┆ 3\Data\Ex │
│            ┆          ┆            ┆ Deductible ┆ ms.gov/fhi ┆           ┆ 5.384     ┆ planation │
│            ┆          ┆            ┆            ┆ …          ┆           ┆           ┆ OfB…      │
│ 1004324545 ┆ 1        ┆ null       ┆ null       ┆ https://bl ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 686        ┆          ┆            ┆            ┆ uebutton.c ┆           ┆ 8 09:36:2 ┆ 3\Data\Ex │
│            ┆          ┆            ┆            ┆ ms.gov/fhi ┆           ┆ 5.384     ┆ planation │
│            ┆          ┆            ┆            ┆ …          ┆           ┆           ┆ OfB…      │
│ …          ┆ …        ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         │
│ 1006359631 ┆ 1        ┆ 0          ┆ N/A        ┆ https://bl ┆ 164660944 ┆ 2026-06-1 ┆ C:\BCDA_V │
│ 211        ┆          ┆            ┆            ┆ uebutton.c ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex │
│            ┆          ┆            ┆            ┆ ms.gov/fhi ┆           ┆ 7.152     ┆ planation │
│            ┆          ┆            ┆            ┆ …          ┆           ┆           ┆ OfB…      │
│ 1006359631 ┆ 1        ┆ A          ┆ Allowed    ┆ https://bl ┆ 164660944 ┆ 2026-06-1 ┆ C:\BCDA_V │
│ 211        ┆          ┆            ┆            ┆ uebutton.c ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex │
│            ┆          ┆            ┆            ┆ ms.gov/fhi ┆           ┆ 7.152     ┆ planation │
│            ┆          ┆            ┆            ┆ …          ┆           ┆           ┆ OfB…      │
│ 1006359631 ┆ 1        ┆ 1          ┆ PHYSICIANS ┆ https://bl ┆ 164660944 ┆ 2026-06-1 ┆ C:\BCDA_V │
│ 211        ┆          ┆            ┆ OR         ┆ uebutton.c ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex │
│            ┆          ┆            ┆ SUPPLIERS  ┆ ms.gov/fhi ┆           ┆ 7.152     ┆ planation │
│            ┆          ┆            ┆ BILLIN…    ┆ …          ┆           ┆           ┆ OfB…      │
│ 1006359631 ┆ 1        ┆ null       ┆ null       ┆ https://bl ┆ 164660944 ┆ 2026-06-1 ┆ C:\BCDA_V │
│ 211        ┆          ┆            ┆            ┆ uebutton.c ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex │
│            ┆          ┆            ┆            ┆ ms.gov/fhi ┆           ┆ 7.152     ┆ planation │
│            ┆          ┆            ┆            ┆ …          ┆           ┆           ┆ OfB…      │
│ 1006359631 ┆ 1        ┆ null       ┆ null       ┆ https://bl ┆ 164660944 ┆ 2026-06-1 ┆ C:\BCDA_V │
│ 211        ┆          ┆            ┆            ┆ uebutton.c ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex │
│            ┆          ┆            ┆            ┆ ms.gov/fhi ┆           ┆ 7.152     ┆ planation │
│            ┆          ┆            ┆            ┆ …          ┆           ┆           ┆ OfB…      │
└────────────┴──────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┘

In [51]:
def process_eob_supporting(df_eob: pl.DataFrame):
    
    def safe_expr(df, source_col, expr, alias):
        if source_col in df.columns:
            return expr.alias(alias)
        return pl.lit(None).alias(alias)
    
    column_names = [
            'id',
            'sequence',
            'timingDate',
            'valueString',
            'supportingInfo_category_code',
            'supportingInfo_code',
            'supportingInfo_code_display',
            'supportingInfo_value',
            'supportingInfo_unit',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
    ]
    
    df_eob_supporting = (
        df_eob
        .filter(pl.col('supportingInfo').is_not_null())
        .select(
            'id',
            'supportingInfo',
            'patient',
            'meta',
            'filename'
        )
        .pipe(flatten, 'supportingInfo')
        .with_columns(
            pl.lit(now).alias('extract_date')
        )
    )
    
    expres = [
        safe_expr(
            df_eob_supporting,
            'valueQuantity',
            pl.col('valueQuantity').struct.field('value'),
            'supportingInfo_value'
        ),
        safe_expr(
            df_eob_supporting,
            'valueQuantity',
            pl.col('valueQuantity').struct.field('unit'),
            'supportingInfo_unit'
        ),
        safe_expr(
            df_eob_supporting,
            'patient',
            pl.col('patient').struct.field('reference').str.split('/').list.get(1),
            'patient_id'
        ),
        safe_expr(
            df_eob_supporting,
            'meta',
            pl.col('meta').struct.field('lastUpdated'),
            'lastUpdated'
        ),
        safe_expr(
            df_eob_supporting,
            'category',
            pl.col('category').struct.field('coding').list.get(0).struct.field('code'),
            'supportingInfo_category_code'
        ),
        safe_expr(
            df_eob_supporting,
            'code',
            pl.col('code').struct.field('coding').list.get(0).struct.field('code'),
            'supportingInfo_code'
        ),
        safe_expr(
            df_eob_supporting,
            'code',
            pl.col('code').struct.field('coding').list.get(0).struct.field('display'),
            'supportingInfo_code_display'
        ),
    ]
    
    df_eob_supporting = (
        df_eob_supporting
        .with_columns(expres)
        .select(column_names)
    )
    
    return df_eob_supporting.to_pandas()

process_eob_supporting(df_eob)

,id,sequence,timingDate,valueString,supportingInfo_category_code,supportingInfo_code,supportingInfo_code_display,supportingInfo_value,supportingInfo_unit,patient_id,lastUpdated,filename,extract_date
0,1004324545686,1,NaT,None,CLM_ADJSTMT_TYPE_CD,0,ORIGINAL,NaN,None,176077134,2026-03-08 09:36:25.384,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
1,1004324545686,2,2024-10-28,None,CLM_IDR_LD_DT,None,None,NaN,None,176077134,2026-03-08 09:36:25.384,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
2,1004324545686,3,NaT,None,RNDRG_PRVDR_FIPS_ST_CD,48,None,NaN,None,176077134,2026-03-08 09:36:25.384,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
3,1004324545686,4,2024-10-21,None,clmrecvddate,None,None,NaN,None,176077134,2026-03-08 09:36:25.384,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
4,1004324545686,5,NaT,None,CLM_CNTRCTR_NUM,04412,"TEXAS - NOVITAS SOLUTIONS, INC. (EFF. 11/17/2012)",NaN,None,176077134,2026-03-08 09:36:25.384,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3602969,1006359631211,6,NaT,00000000,CLM_CLNCL_TRIL_NUM,None,None,NaN,None,164660944,2026-06-16 02:21:57.152,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19
3602970,1006359631211,7,NaT,None,CLM_DISP_CD,01,None,NaN,None,164660944,2026-06-16 02:21:57.152,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19
3602971,1006359631211,8,NaT,None,CLM_QUERY_CD,1,INTERIM BILL,NaN,None,164660944,2026-06-16 02:21:57.152,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19
3602972,1006359631211,9,2026-06-12,None,CLM_NCH_WKLY_PROC_DT,None,None,NaN,None,164660944,2026-06-16 02:21:57.152,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19
3602973,1006359631211,10,NaT,None,CLM_CARR_PMT_DNL_CD,1,PHYSICIAN/SUPPLIER,NaN,None,164660944,2026-06-16 02:21:57.152,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19

In [ ]:
def process_eob_supporting(df_eob: pl.DataFrame):
    
    df_eob_supporting = (
        df_eob
        .filter(pl.col('supportingInfo').is_not_null())
        .select(
            'id',
            'supportingInfo',
            'patient',
            'meta',
            'filename'
        )
        .pipe(flatten, 'supportingInfo')
        .with_columns(
            pl.col('valueQuantity').struct.field('value').alias('supportingInfo_value'),
            pl.col('valueQuantity').struct.field('unit').alias('supportingInfo_unit'),
            pl.col('patient').struct.field('reference').str.split('/').list.get(1).alias('patient_id'),
            pl.col('meta').struct.field('lastUpdated').alias('lastUpdated'),
            pl.col('category').struct.field('coding').list.get(0).struct.field('code').alias('supportingInfo_category_code'),
            pl.col('code').struct.field('coding').list.get(0).struct.field('code').alias('supportingInfo_code'),
            pl.col('code').struct.field('coding').list.get(0).struct.field('display').alias('supportingInfo_code_display'),
            pl.lit(now).alias('extract_date')
        )
        .select(
            'id',
            'sequence',
            'timingDate',
            'valueString',
            'supportingInfo_category_code',
            'supportingInfo_code',
            'supportingInfo_code_display',
            'supportingInfo_value',
            'supportingInfo_unit',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
        )
    )
    return df_eob_supporting.to_pandas()

shape: (3_602_974, 12)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id        ┆ sequence ┆ timingDat ┆ valueStri ┆ … ┆ supportin ┆ patient_i ┆ lastUpdat ┆ filename  │
│ ---       ┆ ---      ┆ e         ┆ ng        ┆   ┆ gInfo_uni ┆ d         ┆ ed        ┆ ---       │
│ str       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ t         ┆ ---       ┆ ---       ┆ str       │
│           ┆          ┆ date      ┆ str       ┆   ┆ ---       ┆ str       ┆ datetime[ ┆           │
│           ┆          ┆           ┆           ┆   ┆ str       ┆           ┆ μs]       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100432454 ┆ 1        ┆ null      ┆ null      ┆ … ┆ null      ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 5686      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 8 09:36:2 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 5.384     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100432454 ┆ 2        ┆ 2024-10-2 ┆ null      ┆ … ┆ null      ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 5686      ┆          ┆ 8         ┆           ┆   ┆           ┆           ┆ 8 09:36:2 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 5.384     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100432454 ┆ 3        ┆ null      ┆ null      ┆ … ┆ null      ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 5686      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 8 09:36:2 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 5.384     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100432454 ┆ 4        ┆ 2024-10-2 ┆ null      ┆ … ┆ null      ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 5686      ┆          ┆ 1         ┆           ┆   ┆           ┆           ┆ 8 09:36:2 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 5.384     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100432454 ┆ 5        ┆ null      ┆ null      ┆ … ┆ null      ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 5686      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 8 09:36:2 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 5.384     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 100635963 ┆ 6        ┆ null      ┆ 00000000  ┆ … ┆ null      ┆ 164660944 ┆ 2026-06-1 ┆ C:\BCDA_V │
│ 1211      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 7.152     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100635963 ┆ 7        ┆ null      ┆ null      ┆ … ┆ null      ┆ 164660944 ┆ 2026-06-1 ┆ C:\BCDA_V │
│ 1211      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 7.152     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100635963 ┆ 8        ┆ null      ┆ null      ┆ … ┆ null      ┆ 164660944 ┆ 2026-06-1 ┆ C:\BCDA_V │
│ 1211      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 7.152     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100635963 ┆ 9        ┆ 2026-06-1 ┆ null      ┆ … ┆ null      ┆ 164660944 ┆ 2026-06-1 ┆ C:\BCDA_V │
│ 1211      ┆          ┆ 2         ┆           ┆   ┆           ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 7.152     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100635963 ┆ 10       ┆ null      ┆ null      ┆ … ┆ null      ┆ 164660944 ┆ 2026-06-1 ┆ C:\BCDA_V │
│ 1211      ┆          ┆           ┆           ┆   ┆           ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 7.152     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [53]:
def process_eob_careteam(df_eob: pl.DataFrame):
    
    def safe_expr(df, source_col, expr, alias):
        if source_col in df.columns:
            return expr.alias(alias)
        return pl.lit(None).alias(alias)
    
    column_names = [
            'id',
            'sequence',
            'provider_name',
            'npi',
            'taxonomy',
            'specialty_code',
            'role',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
    ]
    
    df_eob_careteam = (
        df_eob
        .filter(pl.col('careTeam').is_not_null())
        .select(
            'id',
            'careTeam',
            'patient',
            'meta',
            'filename'
        )
        .pipe(flatten, 'careTeam')
        .with_columns(
            pl.lit(now).alias('extract_date')
        )
    )
    
    expres = [
        safe_expr(
            df_eob_careteam,
            'provider',
            pl.col('provider').struct.field('display'),
            'provider_name'
        ),
        safe_expr(
            df_eob_careteam,
            'provider',
            pl.col('provider').struct.field('identifier').struct.field('value'),
            'npi'
        ),
        safe_expr(
            df_eob_careteam,
            'provider',
            pl.col('provider').struct.field('type'),
            'type'
        ),
        safe_expr(
            df_eob_careteam,
            'qualification',
            pl.col('qualification').struct.field('coding').list.get(0).struct.field('code'),
            'specialty_code'
        ),
        safe_expr(
            df_eob_careteam,
            'qualification',
            pl.col('qualification').struct.field('coding').list.get(-1).struct.field('code'),
            'taxonomy'
        ),
        safe_expr(
            df_eob_careteam,
            'role',
            pl.col('role').struct.field('coding').list.get(1).struct.field('code'),
            'role'
        ),
        safe_expr(
            df_eob_careteam,
            'patient',
            pl.col('patient').struct.field('reference').str.split('/').list.get(-1),
            'patient_id'
        ),
        safe_expr(
            df_eob_careteam,
            'meta',
            pl.col('meta').struct.field('lastUpdated'),
            'lastUpdated'
        ),
    ]
    
    df_eob_careteam = (
        df_eob_careteam
        .with_columns(expres)
        .select(column_names)
    )
    
    return df_eob_careteam.to_pandas()

process_eob_careteam(df_eob)

,id,sequence,provider_name,npi,taxonomy,specialty_code,role,patient_id,lastUpdated,filename,extract_date
0,1004324545686,1,"PRILL, CARRIE",1760915664,363L00000X,50,rendering,176077134,2026-03-08 09:36:25.384,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
1,1004357821502,1,"MUKKAVILLI, VENKATA",1992943658,2084P0800X,26,rendering,176077134,2026-03-08 11:46:00.861,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
2,1004357822988,1,V MUKKAV,1992943658,207QS1201X,C0,attending,176077134,2026-03-07 10:43:55.187,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
3,1004377065539,1,MOBILE X-RAY OF AUSTIN INC,1306845961,293D00000X,47,rendering,176077134,2026-03-09 01:19:56.899,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
4,1004377065539,2,"SMALL, CHRISTIAN",1740546209,None,None,referring,176077134,2026-03-09 01:19:56.899,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0006_2...,06/07/2026 08:17:19
...,...,...,...,...,...,...,...,...,...,...,...
434618,1006337971749,2,"GARDIAL, PAUL",1639170194,None,None,referring,164660944,2026-06-09 01:21:00.072,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19
434619,1006337972436,1,M RENFRO,1003819913,207T00000X,14,attending,164660944,2026-06-09 01:01:43.513,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19
434620,1006337972436,2,M RENFRO,1003819913,207T00000X,14,operating,164660944,2026-06-09 01:01:43.513,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19
434621,1006359631211,1,"REULAND, KURT",1063472579,2085R0202X,30,rendering,164660944,2026-06-16 02:21:57.152,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19
434622,1006359631211,2,"RENFRO, MARK",1003819913,None,None,referring,164660944,2026-06-16 02:21:57.152,C:\BCDA_V3\Data\ExplanationOfBenefit_v3_0449_2...,06/07/2026 08:17:19

In [ ]:
def process_eob_careteam(df_eob: pl.DataFrame):
    df_eob_careteam = (
        df_eob
        .filter(pl.col('careTeam').is_not_null())
        .select(
            'id',
            'careTeam',
            'patient',
            'meta',
            'filename'
        )
        .pipe(flatten, 'careTeam')
        .with_columns(
            pl.col('provider').struct.field('display').alias('provider_name'),
            pl.col('provider').struct.field('identifier').struct.field('value').alias('npi'),
            pl.col('provider').struct.field('type').alias('type'),
            pl.col('qualification').struct.field('coding').list.get(0).struct.field('code').alias('specialty_code'),
            pl.col('qualification').struct.field('coding').list.get(-1).struct.field('code').alias('taxonomy'),
            pl.col('role').struct.field('coding').list.get(1).struct.field('code').alias('role'),
            pl.col('patient').struct.field('reference').str.split('/').list.get(-1).alias('patient_id'),
            pl.col('meta').struct.field('lastUpdated'),
            pl.lit(now).alias('extract_date')
        )
        .select(
            'id',
            'sequence',
            'provider_name',
            'npi',
            'taxonomy',
            'specialty_code',
            'role',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
        )
    )
    return df_eob_careteam.to_pandas()

shape: (434_623, 10)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id        ┆ sequence ┆ provider_ ┆ npi       ┆ … ┆ role      ┆ patient_i ┆ lastUpdat ┆ filename  │
│ ---       ┆ ---      ┆ name      ┆ ---       ┆   ┆ ---       ┆ d         ┆ ed        ┆ ---       │
│ str       ┆ i64      ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str       │
│           ┆          ┆ str       ┆           ┆   ┆           ┆ str       ┆ datetime[ ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ μs]       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100432454 ┆ 1        ┆ PRILL,    ┆ 176091566 ┆ … ┆ rendering ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 5686      ┆          ┆ CARRIE    ┆ 4         ┆   ┆           ┆           ┆ 8 09:36:2 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 5.384     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100435782 ┆ 1        ┆ MUKKAVILL ┆ 199294365 ┆ … ┆ rendering ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 1502      ┆          ┆ I,        ┆ 8         ┆   ┆           ┆           ┆ 8 11:46:0 ┆ 3\Data\Ex │
│           ┆          ┆ VENKATA   ┆           ┆   ┆           ┆           ┆ 0.861     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100435782 ┆ 1        ┆ V  MUKKAV ┆ 199294365 ┆ … ┆ attending ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 2988      ┆          ┆           ┆ 8         ┆   ┆           ┆           ┆ 7 10:43:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 5.187     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100437706 ┆ 1        ┆ MOBILE    ┆ 130684596 ┆ … ┆ rendering ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 5539      ┆          ┆ X-RAY OF  ┆ 1         ┆   ┆           ┆           ┆ 9 01:19:5 ┆ 3\Data\Ex │
│           ┆          ┆ AUSTIN    ┆           ┆   ┆           ┆           ┆ 6.899     ┆ planation │
│           ┆          ┆ INC       ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100437706 ┆ 2        ┆ SMALL,    ┆ 174054620 ┆ … ┆ referring ┆ 176077134 ┆ 2026-03-0 ┆ C:\BCDA_V │
│ 5539      ┆          ┆ CHRISTIAN ┆ 9         ┆   ┆           ┆           ┆ 9 01:19:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 6.899     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 100633797 ┆ 2        ┆ GARDIAL,  ┆ 163917019 ┆ … ┆ referring ┆ 164660944 ┆ 2026-06-0 ┆ C:\BCDA_V │
│ 1749      ┆          ┆ PAUL      ┆ 4         ┆   ┆           ┆           ┆ 9 01:21:0 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 0.072     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100633797 ┆ 1        ┆ M  RENFRO ┆ 100381991 ┆ … ┆ attending ┆ 164660944 ┆ 2026-06-0 ┆ C:\BCDA_V │
│ 2436      ┆          ┆           ┆ 3         ┆   ┆           ┆           ┆ 9 01:01:4 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 3.513     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100633797 ┆ 2        ┆ M  RENFRO ┆ 100381991 ┆ … ┆ operating ┆ 164660944 ┆ 2026-06-0 ┆ C:\BCDA_V │
│ 2436      ┆          ┆           ┆ 3         ┆   ┆           ┆           ┆ 9 01:01:4 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 3.513     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100635963 ┆ 1        ┆ REULAND,  ┆ 106347257 ┆ … ┆ rendering ┆ 164660944 ┆ 2026-06-1 ┆ C:\BCDA_V │
│ 1211      ┆          ┆ KURT      ┆ 9         ┆   ┆           ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 7.152     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
│ 100635963 ┆ 2        ┆ RENFRO,   ┆ 100381991 ┆ … ┆ referring ┆ 164660944 ┆ 2026-06-1 ┆ C:\BCDA_V │
│ 1211      ┆          ┆ MARK      ┆ 3         ┆   ┆           ┆           ┆ 6 02:21:5 ┆ 3\Data\Ex │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 7.152     ┆ planation │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OfB…      │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [37]:
from datetime import datetime

now = datetime.now().strftime('%d/%m/%Y %H:%M:%S')
now

'02/07/2026 15:28:10'

In [93]:
df_eob

shape: (244_161, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ adjudicat ┆ billableP ┆ careTeam  ┆ contained ┆ … ┆ subType   ┆ related   ┆ procedure ┆ filename │
│ ion       ┆ eriod     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ ---       ┆ ---       ┆ list[stru ┆ list[stru ┆   ┆ struct[1] ┆ list[stru ┆ list[stru ┆ str      │
│ list[stru ┆ struct[2] ┆ ct[4]]    ┆ ct[11]]   ┆   ┆           ┆ ct[2]]    ┆ ct[4]]    ┆          │
│ ct[4]]    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ [{{[{"ben ┆ {2024-10- ┆ [{{"PRILL ┆ [{true,"i ┆ … ┆ null      ┆ null      ┆ null      ┆ C:\BCDA_ │
│ efitpayme ┆ 14,2024-1 ┆ , CARRIE" ┆ nsurer-or ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│ ntstatus" ┆ 0-14}     ┆ ,{"http:/ ┆ g",{["htt ┆   ┆           ┆           ┆           ┆ Explanat │
│ ,"B…      ┆           ┆ /hl…      ┆ p:/…      ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ [{{[{"ben ┆ {2024-09- ┆ [{{"MUKKA ┆ [{true,"i ┆ … ┆ null      ┆ null      ┆ null      ┆ C:\BCDA_ │
│ efitpayme ┆ 05,2024-0 ┆ VILLI,    ┆ nsurer-or ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│ ntstatus" ┆ 9-05}     ┆ VENKATA", ┆ g",{["htt ┆   ┆           ┆           ┆           ┆ Explanat │
│ ,"B…      ┆           ┆ {"htt…    ┆ p:/…      ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ [{{[{"ben ┆ {2024-09- ┆ [{{"V     ┆ [{true,"i ┆ … ┆ {[{"outpa ┆ null      ┆ null      ┆ C:\BCDA_ │
│ efitpayme ┆ 05,2024-0 ┆ MUKKAV",{ ┆ nsurer-or ┆   ┆ tient","h ┆           ┆           ┆ V3\Data\ │
│ ntstatus" ┆ 9-05}     ┆ "http://h ┆ g",{["htt ┆   ┆ ttp://hl7 ┆           ┆           ┆ Explanat │
│ ,"B…      ┆           ┆ l7.or…    ┆ p:/…      ┆   ┆ .or…      ┆           ┆           ┆ ionOfB…  │
│ [{{[{"ben ┆ {2024-09- ┆ [{{"MOBIL ┆ [{true,"i ┆ … ┆ null      ┆ null      ┆ null      ┆ C:\BCDA_ │
│ efitpayme ┆ 24,2024-0 ┆ E X-RAY   ┆ nsurer-or ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│ ntstatus" ┆ 9-24}     ┆ OF AUSTIN ┆ g",{["htt ┆   ┆           ┆           ┆           ┆ Explanat │
│ ,"B…      ┆           ┆ INC…      ┆ p:/…      ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ [{{[{"ben ┆ {2024-09- ┆ [{{"J     ┆ [{true,"i ┆ … ┆ {[{"outpa ┆ [{{"https ┆ null      ┆ C:\BCDA_ │
│ efitpayme ┆ 04,2024-0 ┆ CHESTE",{ ┆ nsurer-or ┆   ┆ tient","h ┆ ://bluebu ┆           ┆ V3\Data\ │
│ ntstatus" ┆ 9-04}     ┆ "http://h ┆ g",{["htt ┆   ┆ ttp://hl7 ┆ tton.cms. ┆           ┆ Explanat │
│ ,"B…      ┆           ┆ l7.or…    ┆ p:/…      ┆   ┆ .or…      ┆ gov…      ┆           ┆ ionOfB…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ [{{[{"ben ┆ {2026-05- ┆ [{{"J     ┆ [{true,"i ┆ … ┆ {[{"outpa ┆ null      ┆ null      ┆ C:\BCDA_ │
│ efitpayme ┆ 27,2026-0 ┆ FERGUS",{ ┆ nsurer-or ┆   ┆ tient","h ┆           ┆           ┆ V3\Data\ │
│ ntstatus" ┆ 5-27}     ┆ "http://h ┆ g",{["htt ┆   ┆ ttp://hl7 ┆           ┆           ┆ Explanat │
│ ,"B…      ┆           ┆ l7.or…    ┆ p:/…      ┆   ┆ .or…      ┆           ┆           ┆ ionOfB…  │
│ [{{[{"ben ┆ {2026-05- ┆ [{{"MILLS ┆ [{true,"i ┆ … ┆ null      ┆ null      ┆ null      ┆ C:\BCDA_ │
│ efitpayme ┆ 26,2026-0 ┆ , BRITTNY ┆ nsurer-or ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│ ntstatus" ┆ 5-26}     ┆ ",{"http: ┆ g",{["htt ┆   ┆           ┆           ┆           ┆ Explanat │
│ ,"B…      ┆           ┆ //h…      ┆ p:/…      ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ [{{[{"ben ┆ {2026-05- ┆ [{{"CARIM ┆ [{true,"i ┆ … ┆ null      ┆ null      ┆ null      ┆ C:\BCDA_ │
│ efitpayme ┆ 27,2026-0 ┆ I, KYLIE" ┆ nsurer-or ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│ ntstatus" ┆ 5-27}     ┆ ,{"http:/ ┆ g",{["htt ┆   ┆           ┆           ┆           ┆ Explanat │
│ ,"B…      ┆           ┆ /hl…      ┆ p:/…      ┆   ┆           ┆           ┆           ┆ ionOfB…  │
│ [{{[{"ben ┆ {2026-05- ┆ [{{"M     ┆ [{true,"i ┆ … ┆ {[{"outpa ┆ null      ┆ null      ┆ C:\BCDA_ │
│ efitpayme ┆ 27,2026-0 ┆ RENFRO",{ ┆ nsurer-or ┆   ┆ tient","h ┆           ┆           ┆ V3\Data\ │
│ ntstatus" ┆ 5-27}     ┆ "http://h ┆ g",{["htt ┆   ┆ ttp://hl7 ┆           ┆           ┆ Explanat │
│ ,"B…      ┆           ┆ l7.or…    ┆ p:/…      ┆   ┆ .or…      ┆           ┆           ┆ ionOfB…  │
│ [{{[{"ben ┆ {2026-05- ┆ [{{"REULA ┆ [{true,"i ┆ … ┆ null      ┆ null      ┆ null      ┆ C:\BCDA_ │
│ efitpayme ┆ 27,2026-0 ┆ ND, KURT" ┆ nsurer-or ┆   ┆           ┆           ┆           ┆ V3\Data\ │
│ ntstatus" ┆ 5-27}     ┆ ,{"http:/ ┆ g",{["htt ┆   ┆           ┆           ┆           ┆ Explanat │
│ ,"B…      ┆           ┆ /hl…      ┆ p:/…      ┆   ┆           ┆           ┆           ┆ ionOfB…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
def process_eob_item(df_eob: pl.DataFrame):
    column_names = [
            'id',
            'sequence',
            'diagnosisSequence',
            'informationSequence',
            'location_code',
            'location_display',
            'product_service_code',
            'modifier',
            'product_service_system',
            'quantity_value',
            'revenue_code',
            'revenue_display',
            'service_start',
            'service_end',
            'servicedDate',
            'patient_id',
            'lastUpdated',
            'filename',
            'extract_date'
    ]
    
    df_eob_item = (
        df_eob
        .filter(pl.col('item').is_not_null())
        .select(
            'id',
            'item',
            'patient',
            'meta',
            'filename'
        )
        .pipe(flatten, 'item')
        .with_columns(
            pl.col('productOrService').struct.field('coding').list.get(0).struct.field('code').alias('product_service_code'),
            pl.col('productOrService').struct.field('coding').list.get(0).struct.field('system').str.split('/').list.get(-1).alias('product_service_system'),
            pl.col('quantity').struct.field('value').alias('quantity_value'),
            pl.col('patient').struct.field('reference').str.split('/').list.get(1).alias('patient_id'),
            pl.col('meta').struct.field('lastUpdated').alias('lastUpdated'),
            pl.col('revenue').struct.field('coding').list.get(0).struct.field('code').alias('revenue_code'),
            pl.col('revenue').struct.field('coding').list.get(0).struct.field('display').alias('revenue_display'),
            pl.col('servicedPeriod').struct.field('start').alias('service_start'),
            pl.col('servicedPeriod').struct.field('end').alias('service_end'),
            pl.col('locationCodeableConcept').struct.field('coding').list.get(0).struct.field('code').alias('location_code'),
            pl.col('locationCodeableConcept').struct.field('coding').list.get(0).struct.field('display').alias('location_display'),
            pl.col('diagnosisSequence').list.get(0).alias('diagnosisSequence'),
            pl.col('informationSequence').list.get(0).alias('informationSequence'),
            pl.col('modifier').list.get(0).struct.field('coding').list.get(0).struct.field('code').alias('modifier'),
            pl.lit(now).alias('extract_date'),
            pl.when(pl.col('servicedDate') < MIN_SQL_DATE)
                .then(None)
                .otherwise(pl.col('servicedDate'))
                .alias('servicedDate')
                
        )
        .select(column_names)
    )
    return df_eob_item.to_pandas()

In [144]:
import fastexcel

df = pl.read_csv(r'C:\BCDA_V3\v3-data-dictionary-2.248.0.csv')
urls = df.filter(pl.col('referenceTable').is_not_null()).get_column('referenceTable').to_list()
urls

['https://bluebutton.cms.gov/fhir/CodeSystem/CLM-TYPE-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-SRC-ID',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-SBMT-FRMT-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-PHRMCY-SRVC-TYPE-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-LINE-RX-ORGN-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-BRND-GNRC-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-PTNT-RSDNC-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-LTC-DSPNSNG-MTHD-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-CMPND-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-DRUG-CVRG-STUS-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-CTSTRPHC-CVRG-IND-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-ADJSTMT-TYPE-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-DSPNSNG-STUS-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/Final-Action',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-TYPE-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/System-Type',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-QUERY-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-NRLN-RIC-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-OP-SRVC-TYPE-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-LINE-REV-CTR-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-DDCTBL-COINSRNC-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-ADMSN-TYPE-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-PTNT-STUS-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-MDCR-INSTNL-MCO-PD-SW',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-ADMSN-SRC-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-BILL-FAC-TYPE-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-BILL-CLSFCTN-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-BILL-FREQ-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-FI-ACTN-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-DISP-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-MDCR-NPMT-RSN-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-PPS-IND-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-CNTRCTR-NUM',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-NCH-PRMRY-PYR-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-REV-DSCNT-IND-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-OTAF-IND-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-REV-PACKG-IND-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-REV-PMT-MTHD-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-REV-CNTR-STUS-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-HHA-LUP-IND-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-HHA-RFRL-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-RIC-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/DGNS-DRG-OUTLIER-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-POS-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/PRTCPTNG-IND-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-PRVDR-TYPE-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-CARR-PMT-DNL-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-LINE-HCT-HGB-TYPE-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-MTUS-IND-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-PRCNG-LCLTY-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-PHYSN-ASTNT-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-LINE-CARR-HPSA-SCRCTY-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-PRMRY-PYR-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-FED-TYPE-SRVC-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-PMT-80-100-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-PRCSG-IND-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-SRVC-DDCTBL-SW',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-PRVDR-SPCLTY-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-PRVDR-TYPE-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-ADJSTMT-TYPE-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-RLT-COND-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/CLM-MDCR-NCH-PTNT-STUS-IND-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-MDCR-STUS-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-MDCR-ENTLMT-STUS-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-BUYIN-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-MDCR-ENRLMT-RSN-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-MDCR-ENTLMT-RSN-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-ESRD-STUS-ID',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-DSBLD-STUS-ID',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-DUAL-STUS-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-DUAL-TYPE-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-CVRG-TYPE-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-LIS-EFCTV-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-LIS-COPMT-LVL-CD',
 'https://bluebutton.cms.gov/fhir/CodeSystem/BENE-ENRLMT-EMPLR-SBSDY-SW']

In [116]:
print(urls[0])

shape: (1, 1)
┌─────────────────────────────────┐
│ referenceTable                  │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ https://bluebutton.cms.gov/fhi… │
└─────────────────────────────────┘

In [122]:
df = pl.DataFrame({
    'value': pl.String,
    'description': pl.String,
    'url' : pl.String
})
df

shape: (1, 3)
┌────────┬─────────────┬────────┐
│ value  ┆ description ┆ url    │
│ ---    ┆ ---         ┆ ---    │
│ object ┆ object      ┆ object │
╞════════╪═════════════╪════════╡
│ String ┆ String      ┆ String │
└────────┴─────────────┴────────┘

In [136]:
urls_lst = urls.to_list()
urls_lst

AttributeError: 'DataFrame' object has no attribute 'to_list'

In [134]:
df_url = pd.read_html('https://bluebutton.cms.gov/fhir/CodeSystem/CLM-TYPE-CD')
df_url[0]['Value']

0         1
1         2
2         3
3         4
4        10
       ...
119    2098
120    2099
121    2700
122    2800
123    2900
Name: Value, Length: 124, dtype: int64

In [152]:

rows = []

for url in urls:
    if requests.get(url).status_code != 200:
        continue

    table = pd.read_html(url)[0]

    rows.extend(
        {
            "value": value,
            "description": description,
            "url": url,
        }
        for value, description in zip(
            table["Value"],
            table["Description"]
        )
    )

df = pd.DataFrame(rows)

In [154]:
from Credentials import engine_DEV_Test as engine

df.to_sql('blueButton_LookupTable', engine, index= False)

-1

In [146]:
rows = []


for url in urls:
    if requests.get(url).status_code != 200:
        continue
    df_url = pd.read_html(url)
    rows.append({
        'values': df_url[0]['Value'],
        'description': df_url[0]['Description'],
        'url': url
        })
df = pl.DataFrame(rows)
df
#df_url

shape: (70, 3)
┌───────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ values            ┆ description                     ┆ url                             │
│ ---               ┆ ---                             ┆ ---                             │
│ object            ┆ object                          ┆ str                             │
╞═══════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ 0         1       ┆ 0                         MEDI… ┆ https://bluebutton.cms.gov/fhi… │
│ 1         2       ┆                                 ┆                                 │
│ 2     …           ┆                                 ┆                                 │
│ 0    20000        ┆ 0                        Natio… ┆ https://bluebutton.cms.gov/fhi… │
│ 1    21000        ┆                                 ┆                                 │
│ 2    220…         ┆                                 ┆                                 │
│ 0    S            ┆ 0             STATE-TO-PLAN PD… ┆ https://bluebutton.cms.gov/fhi… │
│ 1    P            ┆                                 ┆                                 │
│ 2    X            ┆                                 ┆                                 │
│ 3    C            ┆                                 ┆                                 │
│ 4 …               ┆                                 ┆                                 │
│ 0     1           ┆ 0                   Community/… ┆ https://bluebutton.cms.gov/fhi… │
│ 1     2           ┆                                 ┆                                 │
│ 2     3           ┆                                 ┆                                 │
│ 3     …           ┆                                 ┆                                 │
│ 0    0            ┆ 0    Not specified              ┆ https://bluebutton.cms.gov/fhi… │
│ 1    1            ┆ 1          …                    ┆                                 │
│ 2    2            ┆                                 ┆                                 │
│ 3    3            ┆                                 ┆                                 │
│ 4 …               ┆                                 ┆                                 │
│ …                 ┆ …                               ┆ …                               │
│ 0    N            ┆ 0            NONE               ┆ https://bluebutton.cms.gov/fhi… │
│ 1    F            ┆ 1       FULL…                   ┆                                 │
│ 2    U            ┆                                 ┆                                 │
│ 3    P            ┆                                 ┆                                 │
│ Na…               ┆                                 ┆                                 │
│ 0     10          ┆ 0                        CHCCP… ┆ https://bluebutton.cms.gov/fhi… │
│ 1     11          ┆                                 ┆                                 │
│ 2     12          ┆                                 ┆                                 │
│ 3  …              ┆                                 ┆                                 │
│ 0    Y            ┆ 0        Yes                    ┆ https://bluebutton.cms.gov/fhi… │
│ 1    N            ┆ 1         No                    ┆                                 │
│ 2    U            ┆ 2   …                           ┆                                 │
│ Name: Val…        ┆                                 ┆                                 │
│ 0    1            ┆ 0             High              ┆ https://bluebutton.cms.gov/fhi… │
│ 1    4            ┆ 1    15% Co…                    ┆                                 │
│ Name: Value, dty… ┆                                 ┆                                 │
│ 0    Y            ┆ 0    Yes                        ┆ https://bluebutton.cms.gov/fhi… │
│ 1    N            ┆ 1     No                        ┆                                 │
│ Name: Value, dty… ┆ Name: Descri…                   ┆                                 │
└───────────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [ ]:
import requests
from bs4 import BeautifulSoup

response = requests.get(url='https://bluebutton.cms.gov/fhir/CodeSystem/CLM-TYPE-CD')
response.raise_for_status()



soup = BeautifulSoup(response.text, 'html.parser')
soup

<!DOCTYPE html>
<html class="usa-js-loading" lang="en"> <head><title>Variable: Claim Type Code - CMS Blue Button API</title><meta charset="utf-8"/><link href="https://bluebutton.cms.gov/fhir/CodeSystem/CLM-TYPE-CD/" rel="canonical"/><meta content="CA CODE IDENTIFYING THE SOURCE AND TYPE OF CLAIM SUBMITTED THROUGH THE MEDICARE OR MEDICAID PROGRAM." name="description"/><meta content="index, follow" name="robots"/><meta content="Variable: Claim Type Code" property="og:title"/><meta content="Website" property="og:type"/><meta content="https://bluebutton.cms.gov/meta/og.jpg" property="og:image"/><meta content="https://bluebutton.cms.gov/fhir/CodeSystem/CLM-TYPE-CD/" property="og:url"/><meta content="CA CODE IDENTIFYING THE SOURCE AND TYPE OF CLAIM SUBMITTED THROUGH THE MEDICARE OR MEDICAID PROGRAM." property="og:description"/><meta content="en_US" property="og:locale"/><meta content="Blue Button" property="og:site_name"/><meta content="https://bluebutton.cms.gov/meta/og.jpg" property="og:image:url"/><meta content="1200" property="og:image:width"/><meta content="630" property="og:image:height"/><meta content="Blue Button" property="og:image:alt"/><meta content="summary_large_image" name="twitter:card"/><meta content="Variable: Claim Type Code" name="twitter:title"/><meta content="https://bluebutton.cms.gov/meta/og.jpg" name="twitter:image"/><meta content="CA CODE IDENTIFYING THE SOURCE AND TYPE OF CLAIM SUBMITTED THROUGH THE MEDICARE OR MEDICAID PROGRAM." name="twitter:description"/><link href="/meta/favicon.svg" rel="icon" type="image/svg+xml"/><link href="/meta/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/><link href="/meta/favicon.ico" rel="shortcut icon"/><link href="/meta/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/><link as="font" crossorigin="anonymous" href="/_astro/open-sans-latin-wght-normal.CWNzRldh.woff2" rel="preload" type="font/woff2"/><link href="/meta/site.webmanifest" rel="manifest"/><meta content="width=device-width, initial-scale=1.0" name="viewport"/><meta content="Astro v6.4.4" name="generator"/><meta content="CMS Blue Button API" name="apple-mobile-web-app-title"/><meta content="4BKCcWU84KzkBcBHkIMbVUWpM5_UWoee6k8YZtMc8SM" name="google-site-verification"/><script type="module">(function(){var e="usa-js-loading",n;document.documentElement.classList.add(e);function t(){document.documentElement.classList.remove(e)}n=setTimeout(t,8e3);function s(){window.uswdsPresent&&(clearTimeout(n),t(),window.removeEventListener("load",s,!0))}window.addEventListener("load",s,!0)})();</script><script>(function(){const TEALIUM_ENV = "prod";
const title = "Variable: Claim Type Code";

      // window is required, otherwise utag_data is locally scoped to this script block
      window.utag_data = {
        content_language: 'en',
        logged_in: false,
        page_type: false,
        page_name: title,
        // default site_environment is 'production', only overwrite in non-prod
        ...(TEALIUM_ENV !== 'prod' ? { site_environment: TEALIUM_ENV } : {}),
      }
    })();</script><script src="https://tealium-tags.cms.gov/cms-bluebutton/prod/utag.sync.js"></script><link href="/_astro/base-layout.BPXFoBFx.css" rel="stylesheet"/><script src="/_astro/page.B_tncCx8.js" type="module"></script>
<script>(window.BOOMR_mq=window.BOOMR_mq||[]).push(["addVar",{"rua.upush":"false","rua.cpush":"false","rua.upre":"false","rua.cpre":"false","rua.uprl":"false","rua.cprl":"false","rua.cprf":"false","rua.trans":"","rua.cook":"false","rua.ims":"false","rua.ufprl":"false","rua.cfprl":"false","rua.isuxp":"false","rua.texp":"norulematch","rua.ceh":"false","rua.ueh":"false","rua.ieh.st":"0"}]);</script>
<script>!function(e){var n="https://s.go-mpulse.net/boomerang/";if("False"=="True")e.BOOMR_config=e.BOOMR_config||{},e.BOOMR_config.PageParams=e.BOOMR_config.PageParams||{},e.BOOMR_config.PageParams.pci=!0,n="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="4TEF3-5C8LB-VHGZE-CUSB2-289FW",function(){function e(){if(!i){var e=document.createElement("script");e.id="boomr-scr-as",e.src=window.BOOMR.url,e.async=!0,o.parentNode.appendChild(e),i=!0}}function t(e){i=!0;var n,t,a,r,d=document,O=window;if(window.BOOMR.snippetMethod=e?"if":"i",t=function(e,n){var t=d.createElement("script");t.id=n||"boomr-if-as",t.src=window.BOOMR.url,BOOMR_lstart=(new Date).getTime(),e=e||d.body,e.appendChild(t)},!window.addEventListener&&window.attachEvent&&navigator.userAgent.match(/MSIE [67]\./))return window.BOOMR.snippetMethod="s",void t(o.parentNode,"boomr-async");a=document.createElement("IFRAME"),a.src="about:blank",a.title="",a.role="presentation",a.loading="eager",r=(a.frameElement||a).style,r.width=0,r.height=0,r.border=0,r.display="none",o.parentNode.appendChild(a);try{O=a.contentWindow,d=O.document.open()}catch(_){n=document.domain,a.src="javascript:var d=document.open();d.domain='"+n+"';void(0);",O=a.contentWindow,d=O.document.open()}if(n)d._boomrl=function(){this.domain=n,t()},d.write("<bo"+"dy onload='document._boomrl();'>");else if(O._boomrl=function(){t()},O.addEventListener)O.addEventListener("load",O._boomrl,!1);else if(O.attachEvent)O.attachEvent("onload",O._boomrl);d.close()}function a(e){window.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!window.BOOMR||!window.BOOMR.version&&!window.BOOMR.snippetExecuted){window.BOOMR=window.BOOMR||{},window.BOOMR.snippetStart=(new Date).getTime(),window.BOOMR.snippetExecuted=!0,window.BOOMR.snippetVersion=12,window.BOOMR.url=n+"4TEF3-5C8LB-VHGZE-CUSB2-289FW";var o=document.currentScript||document.getElementsByTagName("script")[0],i=!1,r=document.createElement("link");if(r.relList&&"function"==typeof r.relList.supports&&r.relList.supports("preload")&&"as"in r)window.BOOMR.snippetMethod="p",r.href=window.BOOMR.url,r.rel="preload",r.as="script",r.addEventListener("load",e),r.addEventListener("error",function(){t(!0)}),setTimeout(function(){if(!i)t(!0)},3e3),BOOMR_lstart=(new Date).getTime(),o.parentNode.appendChild(r);else t(!1);if(window.addEventListener)window.addEventListener("load",a,!1);else if(window.attachEvent)window.attachEvent("onload",a)}}(),"".length>0)if(e&&"performance"in e&&e.performance&&"function"==typeof e.performance.setResourceTimingBufferSize)e.performance.setResourceTimingBufferSize();!function(){if(BOOMR=e.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var n=""=="true"?1:0,t="",a="ddgddefydvncq2soq6zq-f-2dfec55ee-clientnsv4-s.akamaihd.net",o="false"=="true"?2:1,i={"ak.v":"41","ak.cp":"1201726","ak.ai":parseInt("660073",10),"ak.ol":"0","ak.cr":246,"ak.ipv":4,"ak.proto":"http/1.1","ak.rid":"54a0eee6","ak.r":51173,"ak.a2":n,"ak.m":"dscx","ak.n":"essl","ak.cport":1546,"ak.gh":"23.201.104.236","ak.quicv":"","ak.tlsv":"tls1.3","ak.0rtt":"","ak.0rtt.ed":"","ak.csrc":"-","ak.acc":"bbr","ak.t":"1783531443","ak.ak":"hOBiQwZUYzCg5VSAfCLimQ==X8NasSrW9znk1HvjUKkNvONb6vmW5wkMaEfsSvOrg95jWgoqZ125+YVQoOdgc4pM1CxCCqFl3/dPfz+DfSFr/QUM6MDd96lrYtReA4K2ysvT5MFfXBN1jhtbUQNkw3fqkLP6n7D1bb3QIfph+qL2VAklvKMtpiN3K2o7KgBkZJ8ugeENDjyZDaEV0ZEpFNSfQHrCiPc0/yoEn9vC8TVsndkwMvN3fdFrgvQbqmy3DQH154BSx1ggTXmgYZjHkjhl2kLFzpGz/+7BCs7JXpUl1uRVb6WFK9+WuYfbaSKulFIkTmQlhwHFLXGotV2VU191fZbNQHjwWq04UcBj/oj1PGtZC+HZBmVEmHpHJyEOsrmfSrkKYpqmJhFtg5kLetfZ7dw+xQvUkh0MWhcqvBRZkX6pjDupPNnHKrzdJ3+iVqI=","ak.pv":"11","ak.dpoabenc":"","ak.tf":o};if(""!==t)i["ak.ruds"]=t;var r={i:!1,av:function(n){var t="http.initiator";if(n&&(!n[t]||"spa_hard"===n[t]))i["ak.feo"]=void 0!==e.aFeoApplied?1:0,BOOMR.addVar(i)},rv:function(){var e=["ak.cport","ak.cr","ak.csrc","ak.gh","ak.ipv","ak.m","ak.n","ak.ol","ak.proto","ak.quicv","ak.tlsv","ak.0rtt","ak.0rtt.ed","ak.r","ak.acc","ak.t","ak.tf"];BOOMR.removeVar(e)}};BOOMR.plugins.AK={akVars:i,akDNSPreFetchDomain:a,init:function(){if(!r.i){var e=BOOMR.subscribe;e("before_beacon",r.av,null,null),e("onbeacon",r.rv,null,null),r.i=!0}return this},is_complete:function(){return!0}}}}()}(window);</script></head> <body id="page-top"> <a class="usa-skipnav z-top" href="#main-content">Skip to main content</a> <section aria-label="Official website of the United States government" class="usa-banner"> <div class="usa-accordion"> <header class="usa-banner__header"> <div class="usa-banner__inner"> <div class="grid-col-auto"> <img alt="" aria-hidden="true" class="usa-banner__header-flag" src="/_astro/us_flag_small.NpELm1F7.png"/> </div> <div aria-hidden="true" class="grid-col-fill tablet:grid-col-auto"> <p class="usa-banner__header-text">An official website of the United States government</p> <p class="usa-banner__header-action">Here's how you know</p> </div> <button aria-controls="gov-banner-default" aria-expanded="false" class="usa-accordion__button usa-banner__button" type="button"> <span class="usa-banner__button-text">Here's how you know</span> </button> </div> </header> <div class="usa-banner__content usa-accordion__content" id="gov-banner-default"> <div class="grid-row grid-gap-lg"> <div class="usa-banner__guidance tablet:grid-col-6"> <svg aria-hidden="true" class="usa-banner__icon usa-media-block__img" height="64" viewbox="0 0 64 64" width="64"><title>icon-dot-gov</title><path d="m32 0c17.7 0 32 14.3 32 32s-14.3 32-32 32-32-14.3-32-32 14.3-32 32-32zm0 1.2c-17 0-30.8 13.8-30.8 30.8s13.8 30.8 30.8 30.8 30.8-13.8 30.8-30.8-13.8-30.8-30.8-30.8zm11.4 38.9c.5 0 .9.4.9.8v1.6h-24.6v-1.6c0-.5.4-.8.9-.8zm-17.1-12.3v9.8h1.6v-9.8h3.3v9.8h1.6v-9.8h3.3v9.8h1.6v-9.8h3.3v9.8h.8c.5 0 .9.4.9.8v.8h-21.4v-.8c0-.5.4-.8.9-.8h.8v-9.8zm5.7-8.2 12.3 4.9v1.6h-1.6c0 .5-.4.8-.9.8h-19.6c-.5 0-.9-.4-.9-.8h-1.6v-1.6s12.3-4.9 12.3-4.9z" fill="#2378C3" fill-rule="evenodd"></path></svg> <div class="usa-media-block__body"> <p> <strong>Official websites use .gov</strong><br/>A
<strong>.gov</strong> website belongs to an official government organization in the United States.
</p> </div> </div> <div class="usa-banner__guidance tablet:grid-col-6"> <svg aria-hidden="true" class="usa-banner__icon usa-media-block__img" height="64" viewbox="0 0 64 64" width="64"><title>icon-https</title><path d="M32 0c17.673 0 32 14.327 32 32 0 17.673-14.327 32-32 32C14.327 64 0 49.673 0 32 0 14.327 14.327 0 32 0zm0 1.208C14.994 1.208 1.208 14.994 1.208 32S14.994 62.792 32 62.792 62.792 49.006 62.792 32 49.006 1.208 32 1.208zm0 18.886a7.245 7.245 0 0 1 7.245 7.245v3.103h.52c.86 0 1.557.698 1.557 1.558v9.322c0 .86-.697 1.558-1.557 1.558h-15.53c-.86 0-1.557-.697-1.557-1.558V32c0-.86.697-1.558 1.557-1.558h.52V27.34A7.245 7.245 0 0 1 32 20.094zm0 3.103a4.142 4.142 0 0 0-4.142 4.142v3.103h8.284V27.34A4.142 4.142 0 0 0 32 23.197z" fill="#719F2A" fill-rule="evenodd"></path></svg> <div class="usa-media-block__body"> <p> <strong>Secure .gov websites use HTTPS</strong><br/>A
<strong>lock</strong> (
<span class="icon-lock"><svg aria-labelledby="banner-lock-description-default" class="usa-banner__lock-image" focusable="false" height="64" role="img" viewbox="0 0 52 64" width="52" xmlns="http://www.w3.org/2000/svg"> <title id="banner-lock-title-default">Lock</title> <desc id="banner-lock-description-default">Locked padlock icon</desc> <path d="M26 0c10.493 0 19 8.507 19 19v9h3a4 4 0 0 1 4 4v28a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V32a4 4 0 0 1 4-4h3v-9C7 8.507 15.507 0 26 0zm0 8c-5.979 0-10.843 4.77-10.996 10.712L15 19v9h22v-9c0-6.075-4.925-11-11-11z" fill="#000000" fill-rule="evenodd"></path> </svg> </span>) or <strong>https://</strong> means you've safely connected to the .gov website. Share sensitive information
              only on official, secure websites.
</p> </div> </div> </div> </div> </div> </section> <div class="position-sticky top-0 bg-white shadow-1 z-500"> <div class="usa-overlay"></div> <header class="usa-header usa-header--basic"> <div class="usa-nav-container"> <div class="usa-navbar"> <div class="usa-logo"> <a class="usa-link display-flex flex-align-center height-6 maxw-card-lg" data-tealium="navigation" href="/" style="gap: 0.5rem;" to="/"> <svg aria-hidden="true" class="width-5 height-5" fill="none" height="35" viewbox="0 0 35 35" width="35">
<circle cx="17.5" cy="17.5" r="17" stroke="#323a45"></circle>
<circle cx="17.5" cy="17.5" fill="#323a45" r="15.1667"></circle>
<path d="m11.5 18.5h-1.5v6h14.5v-6h-1.5v4h-11.5z" fill="#f7f7f7"></path>
<path d="m17.5 19-5-5h3.5v-7h3.5v7h3z" fill="#f7f7f7"></path>
<g stroke="#f7f7f7">
<path d="m11.5 18.5h-1.5v6h14.5v-6h-1.5v4h-11.5z"></path>
<path d="m17.5 19-5-5h3.5v-7h3.5v7h3z"></path>
</g>

In [170]:
html = """PGRpdj48dWw+PGxpIGlkPSJIaXN0b3J5QW5kUGh5c2ljYWxOb3RlMSI+PHBhcmFncmFwaD5IUEkgKEhpc3Rvcnkgb2YgUHJlc2VudCBJbGxuZXNzKTwvcGFyYWdyYXBoPjx0YWJsZSB3aWR0aD0iMTAwJSIgYm9yZGVyPSIxIj48Y29sZ3JvdXA+PGNvbCB3aWR0aD0iMTAlIi8+PGNvbCB3aWR0aD0iMTAlIi8+PGNvbCB3aWR0aD0iMTUlIi8+PGNvbCB3aWR0aD0iMTUlIi8+PGNvbCB3aWR0aD0iMTUlIi8+PGNvbCB3aWR0aD0iMTUlIi8+PGNvbCB3aWR0aD0i
MjAlIi8+PC9jb2xncm91cD48dGhlYWQ+PHRyPjx0aD5DYXRlZ29yeTwvdGg+PHRoPmMvbzwvdGg+PHRoPkRlbmllczwvdGg+PHRoPlN5bXB0b208L3RoPjx0aD5EdXJhdGlvbjwvdGg+PHRoPkRldGFpbHM8L3RoPjx0aD5Ob3RlczwvdGg+PHRoPkNhdGVnb3J5IE5vdGVzPC90aD48L3RyPjwvdGhlYWQ+PHRib2R5Pjx0cj48dGQgcm93c3Bhbj0iNiI+RnVu
Y3Rpb25hbCBTdGF0dXM8L3RkPjx0ZCByb3dzcGFuPSIzIi8+PHRkIHJvd3NwYW49IjMiLz48dGQgcm93c3Bhbj0iMyI+RnVuY3Rpb25hbCBDb2duaXRpdmUgQXNzZXNzbWVudDo8L3RkPjx0ZCByb3dzcGFuPSIzIi8+PHRkPkZ1bmN0aW9uYWwgQ29nbml0aXZlIEFzc2Vzc21lbnQgMTo6IFN0YXR1cyAxPC90ZD48dGQ+Tm90ZXNAMTIzITwvdGQ+PHRkIHJvd3NwYW49IjYiLz48L3RyPjx0cj48dGQ+RnVuY3Rpb25hbCBDb2duaXRpdmUgQXNzZXNzbWVudCA4OjogMzwvdGQ+PHRkPk5vdGVzQDEyMyE8L3RkPjwvdHI+PHRyPjx0ZD5GdW5jdGlvbmFsIENvZ25pdGl2ZSBBc3Nlc3NtZW50IDExOjogMDEvMDEvMjAyNTwvdGQ+PHRkPk5vdGVzQDEyMyE8L3RkPjwvdHI+PHRyPjx0ZCByb3dzcGFuPSIzIi8+PHRkIHJvd3NwYW49IjMiLz48dGQgcm93c3Bhbj0iMyI+Q29nbml0aXZlIEFzc2Vzc21lbnQ6PC90ZD48dGQgcm93c3Bhbj0iMyIvPjx0ZD5Db2duaXR
pdmUgU3RhdHVzIDQ6IFN0YXR1cyA0PC90ZD48dGQ+Tm90ZXNAMTIzITwvdGQ+PC90cj48dHI+PHRkPkNvZ25pdGl2ZSBTdGF0dXMgMTA6IDQzLjc8L3RkPjx0ZD5Ob3Rlc0AxMjMhPC90ZD48L3RyPjx0cj48dGQ+Q29nbml0aXZlIFN0YXR1cyAxMTogMDEvMDEvMjAyNTwvdGQ+PHRkPk5vdGVzQDEyMyE8L3RkPjwvdHI+PC90Ym9keT48L3RhYmxlPjxicj48L2JyPjwvbGk+PC91bD48L2Rpdj4="""

In [177]:
from io import StringIO
import base64



soup = BeautifulSoup(html, 'lxml')

encoded = soup.find('p').text.strip()

html_2 = base64.b64decode(encoded).decode("utf-8")


#print(html)
df = pd.read_html(StringIO(html_2))[0]
df

,Category,c/o,Denies,Symptom,Duration,Details,Notes,Category Notes
0,Functional Status,NaN,NaN,Functional Cognitive Assessment:,NaN,Functional Cognitive Assessment 1:: Status 1,Notes@123!,NaN
1,Functional Status,NaN,NaN,Functional Cognitive Assessment:,NaN,Functional Cognitive Assessment 8:: 3,Notes@123!,NaN
2,Functional Status,NaN,NaN,Functional Cognitive Assessment:,NaN,Functional Cognitive Assessment 11:: 01/01/2025,Notes@123!,NaN
3,Functional Status,NaN,NaN,Cognitive Assessment:,NaN,Cognitive Status 4: Status 4,Notes@123!,NaN
4,Functional Status,NaN,NaN,Cognitive Assessment:,NaN,Cognitive Status 10: 43.7,Notes@123!,NaN
5,Functional Status,NaN,NaN,Cognitive Assessment:,NaN,Cognitive Status 11: 01/01/2025,Notes@123!,NaN